### ISSUE TITLE
Sanyo DVD RB-SL22

### ISSUE THREAD

**Issue by kw217** [irplus-remote/irplus-codes.github.io#135]
Hi,

Please can you add http://lirc.sourceforge.net/remotes/sanyo/RB-SL22 ? This is my DVD player.

Thanks for a great app!

--KW 8-)

**Comment by irplus-remote** [comment]
Hi, to get it, use V 1.6.3 and use "Update List (online)" button on Add device, then SANYO RB-SL22-DVD. Please tell me if it has worked Thanks

**Comment by kw217** [comment]
Got it and it works - thank you very much!
