### ISSUE TITLE
Mediagate TSDX-IR14

### ISSUE THREAD

**Issue by brianfreud** [irplus-remote/irplus-codes.github.io#145]

**Comment by irplus-remote** [comment]
Hi, did you try if the Microsoft MCE codes can be used? By doing a quick google the remote really seems to be a MCE

**Comment by brianfreud** [comment]
No luck with any of the 4 Microsoft remote types.

**Comment by irplus-remote** [comment]
what phone are you using?

**Comment by brianfreud** [comment]
I'm using a Samsung S4 (non-rooted SGH-i337M model).  Happen to have a code discovery mode or anything I could use to search for the right signals? :)

**Comment by irplus-remote** [comment]
Nope, so if you are sure IR light is going out the emitter it can either be the wrong codes or the receiver itself is not working, can you confirm its working with the original remote?

Try all Microsoft codes again, also this one could work in theory:
HP - RC176xxxx

Im almost sure it's RC6 code, so it doesnt make sense to try others since they are not RC6

http://www.amazon.com/USB-External-Infrared-Receiver-Cable/dp/B00J5NRWFO 
-> Compatible with MCE

**Comment by brianfreud** [comment]
No luck with that HP, nor (having reinstalled each) any of the 4 Microsoft options.  No manufacturer on the IR receiver dongle, but it seems to have been made by TopSeed Technology.  It's the receiver that came with a Media-Gate GP-IR02BK, but has also been shipped with other brands of remotes:

Sold using model numbers GP-IR02BK, HA-IR01SV, and TSGP-IR01 by:
Rosewill Remote control/Rcvr RRC-127 for Win 7
AVS Gear
Media-Gate 
Anyware 
Noah Company 
GP Batteries MediaGate 
Victory MCE Remote Control

**Comment by irplus-remote** [comment]
Does the app work for you with other devices? Like TV? And as asked: Does the original / real remote you have work?

**Comment by brianfreud** [comment]
Good thought; checking on that now - I just upgraded from Raspbmc to OSMC yesterday and hadn't tried the original remote.  I'll update as soon as I can find some batteries.  :P

**Comment by irplus-remote** [comment]
What are you trying to do? I have myself a Rasp with OSMC (and OpenELEC) running. Probably if you just want to remote control it, there should be easier ways like attaching any IR-Diode to its GPIO port or just use a LAN based solution. I think / guess , the receiver is not recognized by the OS or requires some proprietary driver

**Comment by brianfreud** [comment]
I've sortof got it working now.  Hadn't realized that OSMC wiped my remote settings from when I'd set it up with Raspbmc.  So I've now configured OSMC to recognize the remote again, then was able to properly test your app.  

It *does* respond now using the Microsoft - MediaCenter option in the app, if you select lircd-full or rc6-mce-lircd in OSMC.  However, there seems to be an OSMC issue where lirc is still glitchy. See https://discourse.osmc.tv/t/pi2-b-with-rc6-remote-duplicates-key-events/4946/11 .  If you pick either of those remote lirc settings, then every command sent by the remote is received *twice* by OSMC.  Hit up once on the remote, move up twice in a menu, etc.  This applies whether you're using the GP-IR02BK remote or the irplus app.

If you pick the xbox360 specific lirc option, as suggested in that osmc ticket, then the GP-IR02BK remote works properly in OSMC (no double clicking)...  but the irplus app now doesn't work using any of the 4 Microsoft remote options.

I know, I know, it's a funky case...  but given the number of people who bought this specific remote (under any of the brand names) to use with Raspbmc, I'd imagine it won't be a rare problem, as more folks upgrade to the final build of OSMC.  lol  

Side note, there's a few extra buttons on the GP-IR02BK which aren't on the generic RC6 keyset.  http://kodi.wiki/view/Mediagate_GP-IR02BK lists them.  I'll have to mess with custom lirc files this weekend, but hopefully there's enough info there that those buttons might be supported.  :)  That page is slightly wrong, though, for at least my model (which is the one pictured there).  There is no "teletext" button, and the "Movies" button actually reads "Videos".

**Comment by brianfreud** [comment]
Oh, and re "there should be easier ways", yes; I already have Yatse working to control the OSMC.  The OSMC box is hardwired, but the phone is on wifi.  Wifi signal in this room is weak, so anytime I lose wifi, Yatse stops working.  IR, that's not an issue - plus it would let me control the entire setup from a single app.  :D

**Comment by irplus-remote** [comment]
Hi, thanks for the informations. If i have time i might check myself. But this means nothing wrong in the app because i have tested the codes with real MCE and real Xbox -> Here they work. So it must be some error on the "other side". If you post the exact lirc config which worked for you i can add it to the irplus database. (Sorry i dont have the time to crawl all these threads myself :)

**Comment by irplus-remote** [comment]
Im closing old issues, if you still have problems or questions feel free to reopen
