### ISSUE TITLE
Multiple device remote support

### ISSUE THREAD

**Issue by gbritton** [irplus-remote/irplus-codes.github.io#156]
Support for composing a single "universal remote" vie for controlling multiple devices seems to be lacking (even in XML schema). I would like to compose a "TiVo Remote" that acts like theirs, most buttons are TiVo, but TV power and input are from my Samsung TV, and vol+/vol-/mute aid control the soundbar.  This can be partially accomplished by using multiple widgets off separate devices, but isn't very clean.

**Comment by irplus-remote** [comment]
Hi, this would basically need a complete refactoring of logic, and might be added in very far future. Main issue is that each codeset can be in different IR formats. However there is a way to use the macro feature to add buttons from other remotes inside the app too, which might be ok until i found a better way

1. Add all devices you need
2. If you need to reference a different device button on the layout of a device in XML use this notation. Device is in square brackets, button without brackets each component separated by a semicolon

```

 <button label="TV VOL+" macro="true">[SAMSUNG - AA59-00382A];VOL+</button>
    

```

**Comment by gbritton** [comment]
Using macros like this seems sufficient to accomplish what I'm trying to do. I can't figure out how the "Macros" config pane fits into this (if at all, is it incomplete?) Though, I can use it to select button sequences and then copy+paste to get it into the "Edit Buttons" screen. Regardless, I can at least solve this editing the XML to get the right keys everywhere.

One follow-up question, do the devices referenced in macros need to be imported into the list of active devices, or will referencing devices in the database work? 

-- Gerald

----- Reply message -----

**Comment by irplus-remote** [comment]
The macro config pane is intended for quick and easy macro setup like "turn on tv, turn on receiver" on a separate page. 

All devices referenced in macros need to be imported into the list of active devices. If you feel they're cluttering the screen, you can just rename them to be shorter like "TV" , "SB" etc. and reference them via [SB]. 

The reason for this is, that the database is always changing and this would mess up user macros when  a device was renamed or changed internally
