### ISSUE TITLE
AIWA - RC-AAT11 needs key codes from RC-ZAT04

### ISSUE THREAD

**Issue by frankmorgner** [irplus-remote/irplus-codes.github.io#192]
The layout of the AIWA - RC-AAT11 is shown correctly (identical to my RC). Unfortunately the key codes are wrong. Turns out that all the key codes of the AIWA - RC-ZAT04 are working correctly.

So I guess that the codes of RC-AAT11 have been incorrectly imported...

**Comment by irplus-remote** [comment]
Hi, do you really have the RC-AAT11 (Sometimes the layout can be same but codes wrong. The Code are for XR-M201. Is this your device?

**Comment by frankmorgner** [comment]
Yes, RC-AAT11 is written on the top of my RC. I have the aiwa XR-M201.

**Comment by irplus-remote** [comment]
Oh ok i checked again there was indeed an error in the file, i have corrected it, "Add device" -> "Update list " -> Aiwa , RC-AAT11 (irplus V. 1.7.1) and it should work then :) Thanks for reporting!

**Comment by frankmorgner** [comment]
thanks
