### ISSUE TITLE
Craig DVD CVD512a

### ISSUE THREAD

**Issue by ghost** [irplus-remote/irplus-codes.github.io#194]
No Craig brand

**Comment by irplus-remote** [comment]
Hi, if you have the model number please write it down too

**Comment by jesseleehuffman** [comment]
CVD512a

**Comment by irplus-remote** [comment]
I have added generic codes. Could you test and report if they work?
Using v. 1.7.1 from PlayStore: Add device -> Update list -> CRAIG DVD

**Comment by jesseleehuffman** [comment]
Not turning on but it exists now

**Comment by irplus-remote** [comment]
If still interested, could you please retry with latest version and write down which phone you are using?
