### ISSUE TITLE
Denon avr-3803 (rc-921)

### ISSUE THREAD

**Issue by greatleapingcrab** [irplus-remote/irplus-codes.github.io#198]
rc-921 is common to models AVR-1083, AVR-3803S, XV-6760
http://www.newremotecontrol.com/denon/catalog_item.php?catnum=3990839003

Some information available:
http://assets.denon.com/documentmaster/us/avr-3803-ircodes.pdf
http://www.remotecentral.com/cgi-bin/mboard/rc-one4all/thread.cgi?2288
http://files.remotecentral.com/view/3375-8703-1/denon_avr-3803_receiver.html
http://files.remotecentral.com/view/4378-8705-1/denon_avr-3803_receiver.html
http://files.remotecentral.com/view/3839-8704-1/denon_avr-3803_receiver.html

**Comment by irplus-remote** [comment]
Hi, thanks for reporting, will try to add, unfortunately it seems i will have to do it manually because i cant just copy and past the codes. If you want to try yourself in case i take too much time doing it 
 using the avr 3083 code table page this is how it is done. 
(if you do please post the file) 

Will try to make it on the weekend
```
<irplus>
	<device manufacturer="DENON" model="AVR1611" columns="12" format="DENON_K_BINARY" rowSplit="10">
		
		<button label="&#xf011; Dev Off" span="3">001010100100110000000010100001000000000010000110</button>
		<button label="&#xf011; Dev On" span="3">001010100100110000000010100011000000000010001110</button>
		<button label="&#xf011; On" backgroundColor="FFC84334" span="3">001010100100110000000010100001100000000010000100</button>
		<button label="&#xf011; Off" backgroundColor="FFC84334" span="3">001010100100110000000010100011100000000010001100</button>
	 

	</device>
</irplus>
 

```

**Comment by irplus-remote** [comment]
Hi have added RC-921 (Add device -> Update list on latest playstore version) Could you please test if it works ?

**Comment by greatleapingcrab** [comment]
Great, will be back and able to test on Wednesday.

**Comment by greatleapingcrab** [comment]
Confirmed all working properly on my avr3083, apologies for the delay. I
also now see what I was doing wrong when trying it myself - thanks for your
work.

**Comment by irplus-remote** [comment]
Ok thanks for reporting back :)
