### ISSUE TITLE
Samsung AA59-00786a TV remote

### ISSUE THREAD

**Issue by basstom** [irplus-remote/irplus-codes.github.io#202]
Hi,
Lookign for Samsung AA59-00786A F-Series remote controll, but only found the Wave-Files. How can I import/convert them to be used with this marvelous app? Or does anybody have the IR-codes ready to fit into IRplus?
Although, other Samsung remotes work fine, but some buttons are missing which are on this specific remote. I found the HEX-codes for eacht button but if someone has the ready to go codes I would be happy!
Another problem: I use a HTC One M7with latest Android etc., and if I want to record remote signals, it does not work. Can anybody tell me why? I think I have in mind that it worked some months (years?) ago... Is it possible that this feature is blocked by some recent HTC-software-updates? 
A further problem: the import of modified xml files at a computer does not work. After export and editing at a computer (win8) and import into irplus no remote buttons are shown. This would help editing the desired Samsung remote with the above mentioned HEX-codes...
Many thanks for your help and escepcially the app!
Regards, basstom

**Comment by irplus-remote** [comment]
Hi, could you check the AA59-00581A code? It should have all codes your needs. If you can tell me which one is the best "basis" and which buttons are missing / do not work, i might be able to create the exact layout for the 768A.

HTC One m7 stock should be able to record. How did you try? (Try with irplus -> Add device -> Learn) Any error? What happened? 

About the import/export please post a pastebin of the modified file so i can check it

**Comment by basstom** [comment]
Hi,
thanks for the quick answere, will test the remote until this evening!
Recording I tryed as you discribed. No errors, just blinking button in IRplus while pushing remote, even after 2 minutes. Than I quit the process. 
Deleted all files so far, sorry. But I can simulate it, will do it this evening. Where should I paste it?
Regards, basstom

**Comment by irplus-remote** [comment]
You can paste it here too. Also maybe you need to stop the recording manually for HTC (press red button and after 2-3 seconds, repress - eventually it turns green). Also make sure that you are holding the original remote exactly where the IR-blaster is with a distance of about 3cm - not nearer and not further

**Comment by basstom** [comment]
Ok, the mentioned Samsung remote works fine! 
Tried the learning again, but a lot more precisly, now works as well. Wonder if I was that shaky that it wont work the last times.
Thanks alot!! 
Have to post the xml files from export/import tomorrow, maybe that will work then as well... 
Regards, basstom

**Comment by basstom** [comment]
Ok, after some playing around again with import/export I managed to do this properly... I guess you have to start complaining until you do it right...
So far: everything solved!! 
Thank you for your immediate help! Still a great app doing a great job! 
Regards, basstom
