### ISSUE TITLE
Zotac ZBox Nano AD10

### ISSUE THREAD

**Issue by irplus-remote** [irplus-remote/irplus-codes.github.io#203]

**Comment by justinwrobel** [comment]
Here is the power on scan code:  0x8034048e via rc-6

**Comment by irplus-remote** [comment]
Hi, do you have that Zotac box? Are you interested in a full codefile and / or could you test it i i provide one?

**Comment by justinwrobel** [comment]
Hey,
Yeah, I have that box.

Hmm... I could test but I'm not sure how valid it would be. I'm running
openelec on it. Once the thing is on it should respond to just about any
code. Anyway, I'll remove my custom remote file from the box and see if it
respond to your code file.

**Comment by irplus-remote** [comment]
This is the raw rc6 lirc code ( http://pastebin.com/raw/T8Z0aVNs ) 

If you can test with irplus - just choose "AIM" - RC126. Basically those Zotac box use "Standard" MCE Remote Protocol (not exactly RC6)

**Comment by justinwrobel** [comment]
Ok, right, I don't think I fully explained myself: The Zotac box doesn't
respond to the normal MCE power on IR code. I was able to get it to power
on via Harmony remote from which I grabbed that code (0x8034048e) via
ir-keytable over the rc6 protocol. Sorry for the original message I was
just adding that info so that I could transform it later.

So you're right, the Zotac doesn't seem to repond to any of those codes;
however, ir-plus didn't seem to import all of the buttons. I've attached an
image for reference.

Unfortunately, the power on button was missing so I wasn't able to test
that.

Anyway, It seems that 0x8034048e is not in the right format. I'll see if I
can convert it.

**Comment by justinwrobel** [comment]
Just tried MCE power toggle/on/off but to no avail from an unpowered state.
The other keys work once the box is on :-\.

**Comment by irplus-remote** [comment]
Hm strange, but the power on of the real remote works? Can you try to record it with "irrecord" ? Maybe they used a different code then, or they repeat it n-times. (You can set the repeat in irplus too)

**Comment by justinwrobel** [comment]
Ok! Success! I converted the file you gave me to ir-plus format via the
converter <https://irplus-remote.github.io/converter/lirc.html> and I used
the power on button and it powered up! It seems like some of the other
buttons work also.

**Comment by justinwrobel** [comment]
Thanks for all the help! poweron is rc6 but everything else for most use-cases should be MCE. Now, I just need to find a remote that does RC6...

**Comment by irplus-remote** [comment]
Standard RC-6 is common on most Philips remotes. But you could try to record it with irrecord (the box should have lirc installed right?)

**Comment by irplus-remote** [comment]
Hm, so if you use the AIM - RC126 codes . Does everything work ? Or how should i make a working remote? Take the power button from there + MCE buttons? If you made the full working codefile feel free to post it, then i will just use it.

**Comment by justinwrobel** [comment]
Hmm... sadly, the AIM - RC126 doesn't power it on and niether did the two random Phillips that I tried.

So I don't have the remote. I borrowed my friend's Harmony. I can borrow it again but it might be a week or two. 

Yeah, RC6 Power + MCE buttons. I'll post an ir-plus xml file for the zbox but not tonight. Anyway, I'm off 'til later. Thanks again!

**Comment by justinwrobel** [comment]
hmm... I attempted to create a remote mixed with RC6 Power + MCE buttons but I keep getting a "Bad infrared code or not supported by emitter" error when I hit the power buttons. 

I put the RC6 codes into an export from the Microsoft Mediacenter remote. I think there is an issue with the format. Mediacenter uses PRONTO_HEX but the codes you sent are in WINLIRC_RAW. :-(

[Here is my attempt.](https://github.com/justinwrobel/irplus-codes.github.io/blob/master/codes/ZOTAC/ZBOX-CA320NANO-U1.xml)

**Comment by irplus-remote** [comment]
Hi, you can convert those codes so their format match

#1:  0000 006D 0020 0000 0065 0022 0011 0011 0011 0011 0011 0022 0011 0022
0033 0022 0011 0011 0011 0011 0011 0011 0011 0011 0011 0011 0011 0011 0011
0011 0011 0011 0022 0011 0011 0022 0022 0022 0011 0011 0011 0011 0011 0011
0011 0011 0011 0011 0011 0011 0022 0022 0011 0011 0022 0022 0011 0011 0011
0011 0022 0011 0011 0011 0011 0022 0011 0002

#2:  -seems to be the same as #1

#3:  0000 006D 0020 0000 0065 0022 0011 0011 0011 0011 0011 0022 0011 0022
0033 0022 0011 0011 0011 0011 0011 0011 0011 0011 0011 0011 0011 0011 0011
0011 0011 0011 0022 0011 0011 0022 0022 0022 0011 0011 0011 0011 0011 0011
0011 0011 0011 0011 0011 0011 0022 0022 0011 0011 0011 0011 0011 0011 0022
0011 0011 0011 0011 0011 0011 0022 0022 0002



*Regards,*
*~Max*
*Web:* https://irplus-remote.github.io
*Issuetracker*:
https://github.com/irplus-remote/irplus-codes.github.io/issues

**Comment by justinwrobel** [comment]
Awesome! Those codes worked! I am able to power the box on and off at will!

**Comment by irplus-remote** [comment]
Thanks for the file!
