### ISSUE TITLE
SilverCrest SL65/12

### ISSUE THREAD

**Issue by Marc1988m** [irplus-remote/irplus-codes.github.io#206]
Leider fehlt der Receiver SL 65/12.

**Comment by irplus-remote** [comment]
Hi, die Comag-Codes alle mal durchprobiert? SilverCrest sind oft baugleich

**Comment by irplus-remote** [comment]
Hi, habe das manuell jetzt nochmal überprüft folgende codes sind 100% kompatibel mit diesem receiver:

COMAG -> RG 405 DS1

**Comment by Marc1988m** [comment]
Ich bedanke mich recht herzlich, funktioniert alles super. Vllt. kann man in der App einen Eintrag fuer den SilverCrest SL65/12 machen, der dann den Code von der COMAG RG 405 DS1 nutzt, so wuerden zukuenftige Fragen zu den Codes verschwinden =D

Gruß Marc1988m

**Comment by irplus-remote** [comment]
Jo kommt dann mit der nächsten version rein. danke fürs bescheid sagen dass es geklappt hat :)
