### ISSUE TITLE
Import File?

### ISSUE THREAD

**Issue by hurzl** [irplus-remote/irplus-codes.github.io#208]
Can't I just import a file (load from internal storage)?

**Comment by irplus-remote** [comment]
hi yes its possible just save as *.irplus and doubleclick it with a file
explorer

Regards
Max

**Comment by hurzl** [comment]
Nothing happens when I do that

**Comment by hurzl** [comment]
Why?

**Comment by irplus-remote** [comment]
which file explorer? maybe try with es file explorer

**Comment by hurzl** [comment]
Different file explorers, it opens irplus but nothing happens there. Is something wrong with this file https://github.com/irplus-remote/irplus-codes.github.io/issues/207 ?

**Comment by irplus-remote** [comment]
Hi, i have added your file to the database try the following:

(First make sure you are using Version 1.7.5 (211) or higher (check PlayStore for Update) 

1. Add device
2. Update list 
3. Add Paulmann -> Urail 95073

Unfortunatly i dont know why importing didn't work in your case, but if you follow the steps above it will work. I will try to check what went wrong, would you please write down which Android version and Smartphone you have?

**Comment by hurzl** [comment]
> 2. Update list 

Fehler beim Netzwerkzugriff!

android 5.1.1

**Comment by irplus-remote** [comment]
Sicher dass du 1.7.5 (211) hast und dass du Internetzugriff am Handy hast?

**Comment by hurzl** [comment]
ja

**Comment by hurzl** [comment]
jetzt geht es plötzlich, ok

**Comment by irplus-remote** [comment]
jo bei wave war es noch ned drin dachte du hast die normale ;) geht der ir code?

**Comment by hurzl** [comment]
da das audio noch zu schwach ist für die leds keine ahnung ;)

**Comment by irplus-remote** [comment]
mit welchem handy versuchst es und hast die lautstärke auf 100%? Mit oder ohne Widerstand?

**Comment by hurzl** [comment]
Es fehlt ein verstärker. habe einen alten MD-recorder versucht, man sieht es auch blinken mit der kamera, aber es reicht nicht. am handy blinkt nix. Gibt es eine Kompatibilitätsliste?

**Comment by irplus-remote** [comment]
es gibt keine liste aber es sollte gehen.. wenn du magst poste ein bild mit deiner konstruktion und schreib welche leds du genau hast und sag mir das handymodell ein paar hab ich selbst schon getestet

**Comment by hurzl** [comment]
Es kann gar nicht gehen es kommt nur ca. +-1 V raus lg e975

**Comment by irplus-remote** [comment]
der peak sollte höher als 1V sein probier mal aus ob die LED bei einer 1.2V
batterie gut leuchtet. Das sollte sie nämlich.. Es gibt IR LEDs die bei ca.
1V schon leuchten und das langt für ca. 2m Reichweite ca. Ansonsten kannst
du noch über BT Stereo gehen falls das Handy echt nicht genug Spannung
hergibt (Siehe auf meiner Webseite)

**Comment by hurzl** [comment]
die leds sind aus alten fernbedienungen und sind verschieden, vielleicht ist das das problem, die eine ist richtig hell bei 1,4V, die andere nur halb

**Comment by hurzl** [comment]
die sollte ok sein? https://www.conrad.de/de/ir-emitter-950-nm-15-5-mm-radial-bedrahtet-vishay-tsus-5202-cqw-13-184551.html

**Comment by irplus-remote** [comment]
U_f sollte so niedrig wie möglich sein zB 1.2V

https://www.conrad.de/de/ir-emitter-o0212521.html?filterU%3Csub%3EF%3C%2Fsub%3E=1%2C2+V

Und Abstrahlwinkel sorgt dafür dass du nicht so genau zielen musst (höher = besser in dem Fall) 

Evtl. dieser hier:
https://www.conrad.de/de/ir-emitter-940-nm-50-3-mm-radial-bedrahtet-kingbright-l-934f3c-154394.html

**Comment by hurzl** [comment]
oh da gibts sogar eine die im laden vorhanden ist
https://www.conrad.de/de/ir-emitter-940-nm-30-5-mm-radial-bedrahtet-kingbright-l-53f3c-154447.html
weniger winkel bedeutet größere reichweite ;)

**Comment by hurzl** [comment]
Kein Ergebnis, die sind eher noch schwächer ...

**Comment by irplus-remote** [comment]
wie schaut die konstrunktion aus? leuchten sie mit 1.2v batterien gut?
Lautstärke für Medien ist auf 100%? (nicht klingelton)

**Comment by hurzl** [comment]
Es passiert immer noch nichts, wenn ich eine .irplus-Datei versuche zu importieren, diesmal die IR-Variante

**Comment by hurzl** [comment]
Exportieren geht auch nicht nach /storage/emulated/0, er sagt successful. aber da ist keine Datei.

**Comment by irplus-remote** [comment]
Hi notfalls einfach über copy and paste im editor. Siehe Bild) Warum der
file import ned klappt kann ich mir nicht erklären. Hat die App alle
Berechtigungen?

**Comment by hurzl** [comment]
Editor? Bei Export via email will er über NFC beamen.
Nein, SMS, Standort, Kontakte, Anrufe  und Kalender darf er nicht, wozu auch?

**Comment by irplus-remote** [comment]
NFC? SMS?? Frage: Woher hast du die App? Ich hoffe doch aus dem PlayStore.. Die einzige erforderliche Berechtigung ist USB-Speicher

**Comment by hurzl** [comment]
OK eine andere editiern und dann pasten, das klappt.
Auch der Paulmann klappt jetzt! (Mit IR auf S4 mini)

**Comment by hurzl** [comment]
Ja aus dem Playstore, vielleicht spinnt cm-13, ich wundere mich öfter über Berechtigungen
