### ISSUE TITLE
HP LD4210

### ISSUE THREAD

**Issue by EthosOfGnomes** [irplus-remote/irplus-codes.github.io#219]
Require IR remote application for my LD4210.

**Comment by irplus-remote** [comment]
Hi, i think i wont find the codes for this, too rare to find them on the internet.
If you have the real remote see this guide to gather the codes
https://irplus-remote.github.io/?start=codes

**Comment by Amelichev** [comment]
Hello! Try this:
<irplus>
<device manufacturer="HP" model="LD4210_TEST" columns="3" format="PRONTO_HEX">

<button label="POWER" labelSize="20.0" labelColor="FF000000" backgroundColor="FFFFFFFF">0000 006D 0022 0002 0155 00AA 0015 0015 0015 0015 0015 0040 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0040 0015 0040 0015 0015 0015 0040 0015 0040 0015 0040 0015 0040 0015 0040 0015 0015 0015 0015 0015 0015 0015 0040 0015 0015 0015 0015 0015 0015 0015 0015 0015 0040 0015 0040 0015 0040 0015 0015 0015 0040 0015 0040 0015 0040 0015 0040 0015 05ED 0155 0055 0015 0E47</button>

<button label="POWER ON" labelSize="20.0" labelColor="FF000000" backgroundColor="FFFFFFFF">0000 006D 0022 0002 0155 00AA 0015 0015 0015 0015 0015 0040 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0040 0015 0040 0015 0015 0015 0040 0015 0040 0015 0040 0015 0040 0015 0040 0015 0015 0015 0015 0015 0040 0015 0015 0015 0015 0015 0015 0015 0040 0015 0040 0015 0040 0015 0040 0015 0015 0015 0040 0015 0040 0015 0040 0015 0015 0015 0015 0015 05ED 0155 0055 0015 0E47 </button>

<button label="POWER OFF" labelSize="20.0" labelColor="FF000000" backgroundColor="FFFFFFFF">0000 006D 0022 0002 0155 00AA 0015 0015 0015 0015 0015 0040 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0040 0015 0040 0015 0015 0015 0040 0015 0040 0015 0040 0015 0040 0015 0040 0015 0040 0015 0015 0015 0040 0015 0015 0015 0015 0015 0015 0015 0040 0015 0040 0015 0015 0015 0040 0015 0015 0015 0040 0015 0040 0015 0040 0015 0015 0015 0015 0015 05ED 0155 0055 0015 0E47 </button>

<button label="INPUT" labelSize="20.0" labelColor="FF000000" backgroundColor="FFFFFFFF">0000 006D 0022 0002 0155 00AA 0015 0015 0015 0015 0015 0040 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0040 0015 0040 0015 0015 0015 0040 0015 0040 0015 0040 0015 0040 0015 0040 0015 0040 0015 0040 0015 0015 0015 0040 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0040 0015 0015 0015 0040 0015 0040 0015 0040 0015 0040 0015 05ED 0155 0055 0015 0E47 </button>
<button label="ASPECT" labelSize="20.0" labelColor="FF000000" backgroundColor="FFFFFFFF">0000 006D 0022 0002 0155 00AA 0015 0015 0015 0015 0015 0040 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0040 0015 0040 0015 0015 0015 0040 0015 0040 0015 0040 0015 0040 0015 0040 0015 0040 0015 0015 0015 0015 0015 0040 0015 0040 0015 0040 0015 0040 0015 0015 0015 0015 0015 0040 0015 0040 0015 0015 0015 0015 0015 0015 0015 0015 0015 0040 0015 05ED 0155 0055 0015 0E47 </button>
</device>
</irplus>

This codes are from HP LD4200. If it works- I'll add more buttons.

**Comment by irplus-remote** [comment]
Might match with LG 6710V00090N
Closing as there was no more feedback. If you still need this, test file above first and re-open. Thanks
