### ISSUE TITLE
Need a support for handheld

### ISSUE THREAD

**Issue by imanbayev** [irplus-remote/irplus-codes.github.io#220]
Manufacturer is here
http://www.landtech.com.cn
Also need a function of duplicating remotes (ir codes), after pushing all buttons of geniune remote just customize in your app.

**Comment by irplus-remote** [comment]
Hi, the functionality is there. You need hardware to record codes. This is already supported on HTC M8 (or higher) and LG G3 (or higher)
(Add device -> Record). This option is not available on Samsung phones because they have only IR Sender not receiver. I

**Comment by imanbayev** [comment]
Thx, guys! Thanks a lot!!! Im lil bit sorry, but can you give wich smartphones has ir reciver
--
Отправлено из Mail.Ru для Android среда, 27 января 2016г., 02:00 +06:00 от irplus-remote < notifications@github.com> :

**Comment by irplus-remote** [comment]
As said, record is compatible with my app on LG G3, G4, HTC M8,9 .etc. There are some other cheapo chinese smartphones with receiver, but those are not compatible due to missing API access
