### ISSUE TITLE
Electrolux YB1FA 

### ISSUE THREAD

**Issue by akshaybankapure** [irplus-remote/irplus-codes.github.io#225]
I have an Air conditioner in my home of type YB1FA.
company: Electrolux.

**Comment by irplus-remote** [comment]
Hi could you try if these codes work? Just click on the link from Android 

 [Electrolux-Debug](https://raw.githubusercontent.com/irplus-remote/irplus-codes.github.io/master/codes/ELECTROLUX/AC.irplus)

**Comment by irplus-remote** [comment]
Did you try? If still interested reopen the issue
