### ISSUE TITLE
Novabox HD 831 satellite receiver

### ISSUE THREAD

**Issue by atou18** [irplus-remote/irplus-codes.github.io#233]
Please i need for novabox hd 831 satellite receiver
Thk you

**Comment by irplus-remote** [comment]
Hi, could you please get the full model number and manufacturer of it? On the internet i just find Greek Text ;) Maybe it is one of PACE, Samsung or Humax. See sticker on back for model number. It might also be worth a try to try those codes..

**Comment by atou18** [comment]
Solved!! Thank you!! It's Pace!
Στις 10 Μαρ 2016 1:38 ΜΜ, ο χρήστης "irplus-remote" <
notifications@github.com> έγραψε:

**Comment by irplus-remote** [comment]
Hi, thanks for letting me know. Which PACE worked?
