### ISSUE TITLE
PANASONIC TX SERIES

### ISSUE THREAD

**Issue by j62k** [irplus-remote/irplus-codes.github.io#234]
Panasonic TX series does not work with my TX-32C300B tv. Any ideas greatly appreciated. Thanks

**Comment by irplus-remote** [comment]
Hi what phone ?

**Comment by j62k** [comment]
Galaxy Note 3

James Knott

Sent from my android device.

**Comment by irplus-remote** [comment]
Make sure to try all these remote codes. It would be very unlikey that panasonic did change codes for this tv.

-TX-TV-Serie
-TV-Generic
-N2QAYB000239 / 239EASY
- (other N2QAY)
- PlasmaTV2003-2007

**Comment by j62k** [comment]
Thanks for your assistance, I've retried all the codes and still no luck. I also have a soundbar in the SC-HTB series and that works fine.

Thanks

Sent from my android device.

-----Original Message-----

**Comment by irplus-remote** [comment]
Not a single button working from the N2QAYB000239 ? Could you try to turn on the TV with the real remote and then test other buttons?)

**Comment by j62k** [comment]
Tried this with TV Generic, TX Series, N2QAYB000239, N2QAYB000239 Easy, Plasma etc...still no luck

Sent from my android device.

-----Original Message-----

**Comment by irplus-remote** [comment]
Ok, well maybe this TV uses different codes then, unfortunately for now i dont have the exact ones. Whats the code on your genuine remote?

**Comment by irplus-remote** [comment]
I will close this issue as there wasnt a response for a long time. IF still interested please just post the full code of the genuine remote (N2Q......... ) number
