### ISSUE TITLE
No-name Chinese RGB LED controller

### ISSUE THREAD

**Issue by KarlBaumann** [irplus-remote/irplus-codes.github.io#241]
![image](https://cloud.githubusercontent.com/assets/11026930/13793577/d95e6368-eaf7-11e5-94fb-dc76b25a342d.png)

Would be nice to have codes for this one. It comes together with 5meter RGB LED strip. 
Doesn't have any brand or model number.

**Comment by irplus-remote** [comment]
Could you try the TKOOFN Led codes?

**Comment by KarlBaumann** [comment]
Sorry for the Lage reply, I had to reinstall my phone. Now I am in cyanogenmod.

Paulmann seems to fit the besteht so far.
