### ISSUE TITLE
AOC TV LE19W034 

### ISSUE THREAD

**Issue by medatabrain** [irplus-remote/irplus-codes.github.io#244]
The AOC brand is not listed and serching for the model number LE19W034 specific codes yeild zero results in Google.
However, some other software has given partial control

**Comment by irplus-remote** [comment]
Known compatible AOC codes
HANNSPREE - TV-NEC-0-189

Could you try?

**Comment by irplus-remote** [comment]
If still interested please tell if code above worked or not + used Android device. I'm closing for now as there was no answer for a long time
