### ISSUE TITLE
Samsung SMT-H3260

### ISSUE THREAD

**Issue by bigcatisu** [irplus-remote/irplus-codes.github.io#245]
Could you tell me if there is a code that will work for Samsung SMT-H3260  settop box?

**Comment by irplus-remote** [comment]
Hi, did you try the other SMT codes?

**Comment by bigcatisu** [comment]
Hi, Yes I tried all three of the other SMT codes, but none of them worked.

**Comment by irplus-remote** [comment]
[Click me](https://raw.githubusercontent.com/irplus-remote/irplus-codes.github.io/master/codes/SAMSUNG/SMT-H.xml)

Could you try these (directly on Android)

**Comment by bigcatisu** [comment]
That worked! Thanks for the help.

**Comment by irplus-remote** [comment]
Ok, will try to improve the layout too and add it to the list. Thanks for the feedback

**Comment by irplus-remote** [comment]
Cleaning up old issues ;-) is in the irplus DB under  SAMSUNG (DVB .... -> SMT-H)
