### ISSUE TITLE
Acer x1111

### ISSUE THREAD

**Issue by fredfred41** [irplus-remote/irplus-codes.github.io#246]
Hi, looking for acer x1111 dlp projector codes, at least on/off button, is there a way I could add it by myself? thanks

**Comment by irplus-remote** [comment]
Hi, here is the guide: https://irplus-remote.github.io/?start=codes#codes

Are you sure the available Acer Codes dont work though?

**Comment by irplus-remote** [comment]
Closing this since there is no more answer
