### ISSUE TITLE
MDUSA Clock Gone Bad Remote

### ISSUE THREAD

**Issue by stromcooper** [irplus-remote/irplus-codes.github.io#248]
Common in CrossFit boxes all over the world

**Comment by irplus-remote** [comment]
Hi i can only refer to this for now, since i dont think ill be able to find codes for this (at least where i live) rare device. 

https://irplus-remote.github.io#codes

If you have ideas / found any information about the IR codes feel free to post

**Comment by stromcooper** [comment]
I've browsed around the various other remote code sites unsuccessfully.  Also emailed the mfg and received a auto-reply that they're going out of business, so not very hopeful there.  I'm looking for a friend that may have an HTC m7, m8, m9 or LG G3, G4.  Worst case, I'll buy a used one on CraigsList and get the data myself.

Is there a wiki or some other instruction on how to export a given IR device's profile once you've used the "learn" function?  I ultimately want to have that profile on my Note 4 (IR transmit, not receive) and will be happy to share the profile back to this community as well.

Thanks!

**Comment by irplus-remote** [comment]
Hey, My suggestion would be to use a raspberry-pi (or PC) and ir sensor to read the data instead of a phone, since they are more reliable and it wouldbe faster.  Also probably cheaper than a phone.

But however you got the data - you can just use the "Export" menu entry to export the file. 

Note: LG does record in a proprietary format so if you need to move this onto the Note4 this will not work. (Unless you first send me the proprietary once , then i can manually re-read it into an open format by using a Pi)

**Comment by stromcooper** [comment]
I've got a lead on an HTC M8 for just $35.  The Pi would be a cool option, but I can use that M8 as a remote and to stream music via bluetooth to our audio system as well.  Replacement remotes are just $15, but I'd rather get this profile exported and openly available for other tinkers down the road.

Great advice and heads-up about the LG.  I'll try to stick with the HTC devices.

**Comment by stromcooper** [comment]
Thought I had a workable option.  Have an old Dell D610 laptop with IR port and was hoping I could get it to pick up the codes.  Fought with LIRC for a while, several old blog posts, no dice.

Cracked the remote to see what the chips were.  Found a few readable portions:

bw50462-1t

s8050d

Think I'm going to go the HTC phone route to read these codes.  Will simply buy a used / cracked screen off eBay or CraigsList, then resell once I have them.

**Comment by irplus-remote** [comment]
Yeah Irda on laptops is not compatible with Cir of remotes..

However the Info about the IC is a big step.. Ill check the spec later.. So dont buy yet :)

**Comment by irplus-remote** [comment]
Can u make a pic of whole PCB?

**Comment by stromcooper** [comment]
Best photos I could take are attached.  I can't risk breaking the device as we use it daily at the gym.

[Photos (2).zip](https://github.com/irplus-remote/irplus-codes.github.io/files/236829/Photos.2.zip)

**Comment by irplus-remote** [comment]
Damn, nothing found, only some chinese info, but not the full spec sheet :/

**Comment by stromcooper** [comment]
OK, found a friend with a LG G4.  He's going to let me use it tomorrow during lunch to capture the remote codes.  I'll then use the export feature to send the codes to you (binarymode.android@gmail.com?) for conversion, then we can add it to the IR code DB for more to enjoy.

Thanks again for your prompt attention and assistance!

**Comment by irplus-remote** [comment]
Hi, yes this should help, when i have the file ill let you know. Hope it works

**Comment by stromcooper** [comment]
OK, captured on a LG G3 & worked fine using that device, so hopefully translating the propriety format will go well with other devices.  I sent the export to you in email, subject "Export - MDUSA Clock Gone Bad".

**Comment by irplus-remote** [comment]
Um, on my G4 im getting an error while trying to send it. What Android Version is the G3? 

`I/UEI.SmartControl: Blaster SendIrKey...
04-28 20:03:27.358 26180-26192/? D/UEI.SmartControl: ---- Waiting for ACK:
04-28 20:03:27.360 26180-26192/? D/UEI.SmartControl: waitForEvent: 80
04-28 20:03:27.368 26180-30994/? D/UEI.SmartControl: serial port data available: 3 - 1
04-28 20:03:27.369 26180-30994/? D/UEI.SmartControl: serial port data available: 3 - 2
04-28 20:03:27.369 26180-26192/? D/UEI.SmartControl: waitForEvent: duration = 11
04-28 20:03:27.369 26180-26192/? D/UEI.SmartControl: ---- Got ACK: recData = 3
04-28 20:03:27.369 26180-26192/? D/UEI.SmartControl: waitForReply data length:  3
04-28 20:03:27.369 26180-26192/? D/UEI.SmartControl:  Blaster return status: 7
04-28 20:03:27.414 26180-26192/? D/UEI.SmartControl:  Blaster return status: 7
04-28 20:03:27.414 26180-26192/? E/UEI.SmartControl: sendIRWithLearnedCode failed: INVALID_DATA_PACKET_FORMAT
04-28 20:03:27.414 26180-26192/? D/UEI.SmartControl:  --- sendIRWithLearnedData result = 0
04-28 20:03:27.414 26180-26192/? I/UEI.SmartControl: Control.sendIRPattern: 0`

**Comment by irplus-remote** [comment]
It doesnt look good, as it seems LG uses a completely different API and IR format in the G3 (maybe using Android 5?) compared to the G4.. And they have almost no info about how to decrypt those formats..everything in a native library..

**Comment by stromcooper** [comment]
Alright, have the specifics from the capture device.  Model is a VS 985, version 6.0, build mra58k.

If the G3 is just an oddball, I'll look for a HTC One M7, 8 or 9 with a cracked screen.  They sell on ebay daily for $25.  It's worth the $5-10 I'd lose reselling it to have those codes!

**Comment by irplus-remote** [comment]
I guess this can be closed, in case you have any news feel free to re-open it

**Comment by irplus-remote** [comment]
Hi, as said unfortunatly nothing has changed for LG format. It's still encrypted with a unknown key and algorithm, so the LG learned keys will only work on your specific LG device. If you know how to convert them into raw ir sequences let me know :)

**Comment by sprive** [comment]
Hi.  I have one of these remotes, as well as the clock (broken, a WIP to learn and fix how this old-tech works).
I'm new to hardware, what do you need to proceed with support?

If I load this Python script onto CircuitPlayground Express[1], I can dump codes. 

For example, the CLEAR button consistently returns: `Decoded: [29, 23]`
Longer example:
```
Heard 33 Pulses: [306, 1791, 313, 1777, 304, 1797, 307, 733, 275, 772, 273, 773, 272, 1822, 269, 778, 277, 1817, 274, 1819, 272, 1822, 268, 779, 277, 1816, 274, 773, 273, 774, 271, 776, 269]
Decoded: [29, 23]
Heard 33 Pulses: [270, 1823, 277, 1834, 273, 1804, 270, 801, 258, 764, 283, 784, 266, 1831, 250, 789, 256, 1847, 271, 1805, 268, 1817, 274, 773, 272, 1821, 270, 777, 278, 769, 276, 771, 274]
Decoded: [29, 23]
Heard 33 Pulses: [275, 1821, 270, 1821, 269, 1824, 277, 770, 275, 799, 247, 799, 272, 1795, 270, 777, 281, 1813, 275, 1845, 251, 1827, 282, 754, 277, 1816, 277, 779, 264, 774, 271, 789, 270]
Decoded: [29, 23]
Heard 33 Pulses: [271, 1823, 268, 1826, 275, 1818, 272, 775, 271, 776, 269, 778, 277, 1816, 277, 770, 273, 1820, 271, 1823, 277, 1817, 274, 772, 273, 1824, 267, 777, 268, 778, 277, 770, 275]
Decoded: [29, 23]
Heard 33 Pulses: [277, 1817, 273, 1820, 271, 1823, 277, 770, 276, 771, 274, 772, 273, 1821, 270, 777, 268, 1826, 275, 1819, 272, 1821, 270, 777, 278, 1818, 272, 772, 274, 773, 272, 775, 270]
Decoded: [29, 23]```





[1] - https://learn.adafruit.com/remote-control-tree-ornament-with-circuit-playground-express/code-the-circuit-playground-express#
