### ISSUE TITLE
support for cristor atlas 200s tv box

### ISSUE THREAD

**Issue by addoull** [irplus-remote/irplus-codes.github.io#252]
The actual config for atlas doesn't seem to work for 200s box.

**Comment by irplus-remote** [comment]
Hi, try this code (click from android device), this should work.

[Atlas 200s](https://raw.githubusercontent.com/irplus-remote/irplus-codes.github.io/master/codes/CRISTOR%20ATLAS/HD-200S.xml)

**Comment by celoovs** [comment]
> Oi, tente este código (clique no dispositivo Android), isso deve funcionar.
> 
> [Atlas 200s](https://raw.githubusercontent.com/irplus-remote/irplus-codes.github.io/master/codes/CRISTOR%20ATLAS/HD-200S.xml link no work
