### ISSUE TITLE
MXQ Ott Media (Kodi)

### ISSUE THREAD

**Issue by gemsjams** [irplus-remote/irplus-codes.github.io#253]
I have a mxq ott media kodi  streaming box and 8 am struggling to find a app for my android to control the main meue of this box through my ir blaster. Can anyone help please. I've been looking for days

**Comment by irplus-remote** [comment]
Hi if its a wifi connected kodi box i can recommend to use this

https://play.google.com/store/apps/details?id=org.xbmc.kore

If you need the IR codes please provide the lirc file of the box

**Comment by gemsjams** [comment]
What is the lirc file please?

**Comment by irplus-remote** [comment]
Kodi's IR works with LIRC. See here

http://kodi.wiki/view/HOW-TO:Set_up_LIRC

The file should be in   /etc/lirc/lircd.conf
