### ISSUE TITLE
Haier Air Conditioner HWR05xC6

### ISSUE THREAD

**Issue by BQDavis** [irplus-remote/irplus-codes.github.io#260]
I lost the remote and making this code was the only way for me to get it to go from fan to cooling.

I imported it by removing the .txt and emailing it to myself then opening the attachment.  Hope this helps someone.

[HAIER - hwr05xc6.irplus.txt](https://github.com/irplus-remote/irplus-codes.github.io/files/414420/HAIER.-.hwr05xc6.irplus.txt)

**Comment by irplus-remote** [comment]
Hi, Thanks will be added for the next version! 

BTW: you can use *.irplus ending instead of txt for easy import from File System

**Comment by BQDavis** [comment]
Yeah I got an error when I uploaded it as .irplus, 
"Unfortunately, we don’t support that file type. with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP." 

So I guess sending it as a zip is better
[HAIER - hwr05xc6.zip](https://github.com/irplus-remote/irplus-codes.github.io/files/415284/HAIER.-.hwr05xc6.zip)
