### ISSUE TITLE
include sony rm-amu096 for cmt-mx750ni (hifi mini system)

### ISSUE THREAD

**Issue by aanno** [irplus-remote/irplus-codes.github.io#263]
I've succeeded in reading the IR codes from sony rm-amu096 for cmt-mx750ni (hifi mini system) with a raspberry pi zero!

[sony-rm-amu096--cmt-mx750Ni.txt.zip](https://github.com/irplus-remote/irplus-codes.github.io/files/418614/sony-rm-amu096--cmt-mx750Ni.txt.zip)
[sony-rm-amu096--cmt-mx750Ni.xml.zip](https://github.com/irplus-remote/irplus-codes.github.io/files/418616/sony-rm-amu096--cmt-mx750Ni.xml.zip)

**Comment by irplus-remote** [comment]
Thanks for providing the codes. I have created the layout and added the code into main db :) "Add device" -> "Update list" -> "SONY" -> RM-AMU096

(Available in about 5minutes)
