### ISSUE TITLE
Edifier R2730DB remote

### ISSUE THREAD

**Issue by mbakulin** [irplus-remote/irplus-codes.github.io#264]
I've uploaded a remote for Edifier R2730DB audio system. Please include it, if you deem it worthy :)
[EDIFIER - R2730DB.txt](https://github.com/irplus-remote/irplus-codes.github.io/files/430726/EDIFIER.-.R2730DB.txt)

**Comment by irplus-remote** [comment]
Thanks! Will be done :+1:
