### ISSUE TITLE
DK Digital audio system 5.1

### ISSUE THREAD

**Issue by ionutbvu** [irplus-remote/irplus-codes.github.io#265]
Hi! My remote control for this audio system DK Digital MODEL NO:  AS-40-1 is damage...it possible to update the app whit my device ? I use a samsung galaxy s5 and irplus 1.8.5 (build 233)

**Comment by irplus-remote** [comment]
Hi, could you please try the attached file  (rename from *.txt to *.irplus)

[AS40-1.txt](https://github.com/irplus-remote/irplus-codes.github.io/files/446939/AS40-1.txt)

**Comment by ionutbvu** [comment]
Hi! i try to attache this file...but is not work...and buttons look different. 
this is the broken remote
![14194396_10154643757093072_340099372_n](https://cloud.githubusercontent.com/assets/21269115/18140754/8fdbf3ac-6fbf-11e6-9c38-b441c6c71602.jpg)

and irplus

![14193571_10154643761123072_54797296_n](https://cloud.githubusercontent.com/assets/21269115/18140813/d0c90288-6fbf-11e6-854c-6caf9d68c920.png)

**Comment by ionutbvu** [comment]
![soundsystem-dk-digital](https://cloud.githubusercontent.com/assets/21269115/18141069/bc4e5dac-6fc0-11e6-860e-3788324ba214.jpg)

**Comment by irplus-remote** [comment]
Hi, yes i know that the buttons are different, but the codeset should work 
for
AS20, AS120, AS40-1, AS40-2

Are you sure the IR-receiver of those speakrs work?

Do other devices like TV work with irplus?

**Comment by ionutbvu** [comment]
Hi! IR-receiver of  speakrs is ok because a single button on the remote worked (reset buuton). 
On the tv i can't test because I can't find the remote model ( BN59-01198Q SAMSUNG UE40J6200) but the ir on the phone work with other app for tv.

**Comment by irplus-remote** [comment]
You can try other BN59, for example 01015A or similar

**Comment by ionutbvu** [comment]
I think the problem is between the phone and irplus, I put a camera in front of the ir and not blinking... i test the phone app (peel smart remote) and blink....  with irplus doesn't  work :(

**Comment by irplus-remote** [comment]
You have a regular Galaxy S5 ? Did you change anything in the app settings? Can you try to reinstall? Are you using a custom rom?

In case of a custom rom you might need to change the pulse setting

**Comment by ionutbvu** [comment]
I reinstall the app and now is working. Thanx a lot !!!

**Comment by irplus-remote** [comment]
Ah cool ! Could you please rename the buttons of the DK correctly via edit please? And then send me back the result?

**Comment by ionutbvu** [comment]
[DK DIGITAL - AS 40 - 1.zip](https://github.com/irplus-remote/irplus-codes.github.io/files/450768/DK.DIGITAL.-.AS.40.-.1.zip)

**Comment by irplus-remote** [comment]
Thanks, will include them as you posted. I guess this issue can be closed :)
