### ISSUE TITLE
Edifier studio 7/8 (r2700/r2800)

### ISSUE THREAD

**Issue by zaibatel** [irplus-remote/irplus-codes.github.io#267]
I've uploaded a remote for Edifier R2800 audio system. Please include it.
[EDIFIER - r2800.zip](https://github.com/irplus-remote/irplus-codes.github.io/files/491745/EDIFIER.-.r2800.zip)
![r2600-remote](https://cloud.githubusercontent.com/assets/16042954/18816452/7b7c0b9a-8374-11e6-91a6-b0d1fdf29307.jpg)

**Comment by irplus-remote** [comment]
Included in 1.8.6, Thanks for the file 👍
