### ISSUE TITLE
Sylvania mosaic flexlight

### ISSUE THREAD

**Issue by VinnyCapelli** [irplus-remote/irplus-codes.github.io#269]
Hi , trying to find a way to control a Sylvania Mosaic Flexlight, FCC Model #72599 with an HTC.

Edit: removed big picture, fcc is enough

**Comment by irplus-remote** [comment]
Hi, which HTC? You can use the Learning-Feature toget the code from the genuine remote.

**Comment by VinnyCapelli** [comment]
Hello,

HTC M9 , I have lost the remote sadly. I thought about trying to see if I
could find a display model at a home improvement store nearby though.

**Comment by irplus-remote** [comment]
Maybe try one of those brands:

LED-UNIVERSUM
LILUCO
LEXMAN
TKOOFN
REVOLTEC
PAULMANN
LIVARNO

**Comment by VinnyCapelli** [comment]
None map perfectly but I finally found one that would turn off the lights,
thank you for your work on this app.  If you plan on building a layout for
the Sylvania let me know and I will test it out.

Thanks again

**Comment by irplus-remote** [comment]
Hi, which one does it?
