### ISSUE TITLE
JVC RM-C1514 RM-C1100 RM-C1512 

### ISSUE THREAD

**Issue by lulbehanger777** [irplus-remote/irplus-codes.github.io#270]
RM-C1100 TV

**Comment by irplus-remote** [comment]
Hi, will try to add it. Just for info: Did you try the available JVC TV codes (Tv-Generic e.g) to see if they already are compatible with it?

**Comment by irplus-remote** [comment]
Available JVC codes should work , tested 

e.g. RM-C14G
