### ISSUE TITLE
BenQ-W1100

### ISSUE THREAD

**Issue by lumapu** [irplus-remote/irplus-codes.github.io#271]
Hello,

I captured and tested the NEC Codes for the projector W1100 manufactured by BenQ
Can you add the remote to your database?

Thanks,
lumapu

[BenQ_W1100.irplus.txt](https://github.com/irplus-remote/irplus-codes.github.io/files/518559/BenQ_W1100.irplus.txt)

**Comment by irplus-remote** [comment]
Hi Thanks, will add them, though i noticed that some of the available Benq codes are the same, so i will check if i can somehow "unify" them to avoid having duplicate codefiles :)
