### ISSUE TITLE
Sony TA-V715T Stereo Integrated Amplifier

### ISSUE THREAD

**Issue by enzyx** [irplus-remote/irplus-codes.github.io#273]
Here are the remote codes for the Sony TA-V715T Stereo Integrated Amplifier:

[SONY_TA_V715T.txt](https://github.com/irplus-remote/irplus-codes.github.io/files/537555/SONY_TA_V715T.txt)

**Comment by irplus-remote** [comment]
Thanks, will add them to the list soon :)
