### ISSUE TITLE
no-name LED strip

### ISSUE THREAD

**Issue by cboltz** [irplus-remote/irplus-codes.github.io#274]
Some years ago, I bought an no-name LED strip with a 24 button remote control. I tested various LED remotes included in irplus, but none of them worked. The "Paulmann" one at least caused some reactions (the LED strip changed colors etc. - but things were completely mixed up - for example, the blue-ish button at the bottom of the green column switched to red).

Long story short - I sorted out all the mixed-up buttons and created a new remote that works for my LED strip. It's attached as [LED cb.irplus](https://github.com/irplus-remote/irplus-codes.github.io/files/546488/LED.cb.irplus.txt). Can you please add this layout to irplus? ;-)  (feel free to change the name to something more useful)

BTW: Is there a way to manually sort the remotes in the top bar? It seems new ones are always appended on the right, but I'd prefer manual sorting ;-)

**Comment by irplus-remote** [comment]
Hey. Sure thanks for the file. Is it really noname? I kinda have no idea in which brand i should add it :) Nothing written on it?

You can sort the remotes in the rooms view (drag and drop) 

Hope it helps :)

**Comment by cboltz** [comment]
The controller only has the input and output voltage on it, and "+BRG IR" to describe the cabling - so it's really no-name (well, unless there's something on the back - but I won't remove the screw to detach it from the wall ;-)
Also, the remote only has some instructions about opening the battery case on it, but no brand name, not even a part number.

I'd propose to use a generic "LED strip" brand ;-)

Maybe it would even be helpful to have the existing remotes for LED strips (also) in that category - without the manufacturer list in issue 241, I would not even have found the "Paulmann" layout which gave me at least working codes.

Oh, and thanks for the pointer about sorting!

**Comment by irplus-remote** [comment]
Yeah thats a good idea, ill probably add yours as noname under the new "LED-Lights" brand. And will create "symlinks" to the other files like paulmann into that category too - so users should find them more easily

**Comment by irplus-remote** [comment]
Changes made for next version (coming soon)
