### ISSUE TITLE
Importing LIRC files from local storage doesn't work

### ISSUE THREAD

**Issue by newton33** [irplus-remote/irplus-codes.github.io#280]
If i choose import from the menu, point to a lirc file stored in internal memory or sd-card and press OK absolutely nothig happens. I've tried several files and locations. Importing from the online LIRC db works.
I'm using a Xiaomi Redmi 3s running CM13 (Marshmallow).

**Comment by irplus-remote** [comment]
Hi, could you send me one of those files? Are you sure that the app has the permission to access storage? Though "nothing happens" is bad, at least there should be an error, so i will watch into that.

**Comment by newton33** [comment]
Hi, here are the files i've tried:
[BN59-00940A.txt](https://github.com/irplus-remote/irplus-codes.github.io/files/650290/BN59-00940A.txt)
[BN59-00869A.txt](https://github.com/irplus-remote/irplus-codes.github.io/files/650292/BN59-00869A.txt)
[RM-SA5U.txt](https://github.com/irplus-remote/irplus-codes.github.io/files/650291/RM-SA5U.txt)
I've tried also witout extension and extension changed to .lirc.
If I enter a path that doesn't exist, I don't get an error message either. 
The app has permission for storage.

**Comment by irplus-remote** [comment]
Hi, could you make a screenshot of the selection you did before pressing "OK" (with full path visible)? (Note: Please use the latest version). Unfortunately i could not reproduce until now. So if this still is not working for you, feel free to re-open with the requested information
