### ISSUE TITLE
Dyno Jet SS7411D

### ISSUE THREAD

**Issue by SingularityB** [irplus-remote/irplus-codes.github.io#286]
Please, add support for Dyno Jet SS7411D. 
This is 5.1 acoustic system.

**Comment by Amelichev** [comment]
Hello! Here the codes:

<irplus>
<device manufacturer="" model="duno" columns="4" format="WINLIRC_RAW" repeatheader="false">
<button label="power" labelSize="12.0">8710 4472 494 1664 520 572 520 572 520 598 520 572 520 572 520 572 520 572 520 598 520 1664 520 1690 520 1664 520 1690 520 1690 494 1664 520 1690 520 572 520 572 520 1690 520 1664 520 572 520 598 520 572 520 572 520 1690 494 1664 520 572 520 598 494 1664 520 1690 520 1664 520 1690 520 43316 8788 2262 520 96148 8736 2236 520 96148</button>
<button label="mute" labelSize="12.0">8710 4498 494 1690 520 572 520 572 520 572 520 598 520 572 520 572 520 572 520 572 520 1690 520 1664 520 1690 520 1690 520 1664 520 1690 520 1664 520 1690 520 572 520 1690 520 1664 520 572 520 598 468 572 520 572 520 572 520 1690 520 572 520 572 520 1690 468 1664 520 1690 520 1664 520 43290 8788 2262 520 96122 8762 2262 520 96122</button>
<button label="1" labelSize="12.0">8762 4524 520 1690 520 598 520 598 520 572 520 572 520 598 520 572 520 572 520 598 520 1690 520 1690 520 1716 520 1690 520 1716 520 1690 520 1690 520 598 520 572 520 572 520 598 520 572 520 572 520 598 520 598 520 1690 520 1716 520 1690 520 1690 520 1690 520 1690 520 1716 520 1690 520 43836 8788 2288 520 97266 8788 2288 520 97266</button>
<button label="2" labelSize="12.0">8658 4446 494 1664 494 572 520 572 520 572 494 572 520 572 520 572 494 572 520 572 520 1638 520 1664 520 1638 520 1664 520 1638 520 1664 520 1638 520 1664 520 572 494 572 520 572 520 572 494 572 520 572 520 572 494 572 520 1664 468 1664 520 1664 468 1664 520 1664 494 1664 520 1664 520 42744 8684 2236 520 94926 8684 2236 520 94900</button>
<button label="3" labelSize="12.0">8684 4446 494 1638 520 572 520 572 520 546 520 572 520 572 520 546 520 572 520 572 494 1664 520 1664 468 1664 520 1664 494 1664 520 1664 494 1664 520 572 520 1638 520 572 520 572 494 572 520 572 520 572 494 572 520 1664 520 546 520 1664 520 1638 520 1664 520 1638 520 1664 520 1638 520 42744 8710 2210 520 94926 8684 2236 494 94926</button>
<button label="4" labelSize="12.0">8736 4498 494 1690 520 572 520 572 520 572 520 598 468 572 520 572 520 572 520 572 520 1690 520 1664 520 1690 520 1664 520 1690 520 1690 468 1664 520 1690 520 1664 520 572 520 572 520 598 520 572 520 572 520 572 520 572 520 572 520 1690 520 1690 468 1664 520 1690 520 1664 520 1690 520 43290 8762 2262 520 96122 8710 2236 520 96122</button>
<button label="5" labelSize="12.0">8736 4498 494 1690 494 572 520 572 520 572 520 572 520 572 520 598 494 572 520 572 520 1664 520 1690 520 1664 520 1690 520 1664 520 1690 520 1664 520 572 520 598 520 1664 520 572 520 572 520 598 494 572 520 572 520 1664 520 1690 520 572 520 1690 468 1664 520 1664 520 1690 520 1690 494 43264 8762 2262 520 96044 8736 2262 520 96044</button>
<button label="6" labelSize="12.0">8762 4524 520 1690 520 572 520 598 520 598 520 572 520 572 520 598 520 598 520 572 520 1690 520 1716 520 1690 520 1690 520 1716 520 1690 520 1716 520 1716 494 572 520 1690 520 598 520 572 520 572 520 598 520 598 494 572 520 1690 520 598 520 1690 520 1690 520 1716 494 1690 520 1716 520 43862 8788 2288 494 97344 8814 2288 520 97344</button>
<button label="7" labelSize="12.0">8736 4498 494 1690 520 572 520 572 520 572 520 572 520 598 468 572 520 572 520 572 520 1690 468 1664 520 1690 520 1664 520 1690 520 1664 520 1690 520 572 520 1664 520 1690 520 572 520 572 520 598 468 572 520 572 520 1664 520 598 494 572 520 1664 520 1690 520 1664 520 1690 520 1664 520 43290 8814 2262 468 96096 8736 2236 520 96122</button>
<button label="8" labelSize="12.0">8762 4524 520 1690 520 572 520 598 520 598 520 572 520 572 520 598 520 598 520 572 520 1690 520 1716 520 1690 520 1716 520 1690 520 1690 520 1716 520 1690 520 1690 520 1716 520 572 520 572 520 598 520 598 520 572 520 572 520 598 520 572 520 1690 520 1716 520 1690 520 1690 520 1716 520 43836 8788 2288 520 97344 8788 2288 520 97344</button>
<button label="9" labelSize="12.0">8762 4524 520 1690 520 572 520 598 520 598 520 572 520 572 520 598 520 572 520 572 520 1716 520 1690 520 1690 520 1716 520 1690 520 1690 520 1716 520 572 520 572 520 598 520 1690 520 572 520 598 520 598 520 572 520 1690 520 1716 520 1690 520 572 520 1716 520 1690 520 1690 520 1716 494 43836 8788 2288 520 97344 8788 2288 520 97344</button>
<button label="0" labelSize="12.0">8762 4602 494 1716 520 598 520 572 520 598 520 598 520 598 520 572 520 598 520 598 520 1742 520 1716 520 1716 520 1742 520 1716 520 1716 520 1716 520 598 520 1742 520 598 520 1742 520 598 520 598 520 572 520 598 520 1716 520 598 520 1716 520 598 520 1716 520 1716 520 1742 520 1716 520 44382 8788 2314 520 98540 8814 2288 520 98540</button>
<button label="10+" labelSize="12.0">8762 4524 520 1690 520 572 520 598 520 598 520 572 520 572 520 598 520 598 520 572 520 1690 520 1716 520 1690 520 1690 520 1716 494 1690 520 1716 520 1690 520 1690 520 598 520 1690 520 572 520 598 520 598 520 572 520 572 520 598 520 1716 494 572 520 1690 520 1716 494 1690 520 1716 520 43862 8788 2262 520 97344 8788 2288 520 97344</button>
<button label="stop" labelSize="12.0">8762 4524 520 1690 520 572 520 598 520 598 520 572 520 572 520 598 520 598 494 572 520 1716 520 1716 494 1690 520 1716 520 1690 520 1690 520 1716 520 1690 520 572 520 1716 520 572 520 572 520 598 520 1716 494 572 520 598 520 1716 520 572 520 1690 520 1716 494 1690 520 598 520 1716 494 43836 8788 2288 520 97344 8788 2288 520 97344</button>
<button label="play/pause" labelSize="12.0">8736 4498 494 1664 520 598 520 572 520 572 520 572 520 572 520 572 520 598 494 572 520 1690 520 1664 520 1690 520 1664 520 1690 520 1664 520 1690 520 572 520 572 520 1664 520 598 494 572 520 572 520 1664 520 572 520 1690 520 1664 520 598 520 1664 520 1690 468 1664 520 572 520 1690 520 43238 8762 2262 520 96018 8762 2236 520 96044</button>
<button label="&lt;&lt;" labelSize="12.0">8710 4498 494 1664 520 598 520 572 520 572 520 572 520 572 520 572 520 598 468 572 520 1664 520 1690 520 1664 520 1690 520 1664 520 1690 520 1664 520 572 520 572 520 598 494 572 520 572 520 572 520 1664 520 598 520 1664 520 1690 468 1664 520 1664 520 1690 520 1664 520 598 468 1664 520 43212 8788 2236 520 95992 8762 2262 494 95966</button>
<button label="&gt;&gt;" labelSize="12.0">8762 4524 520 1690 520 572 520 598 520 598 520 572 520 572 520 598 520 598 494 572 520 1690 520 1716 520 1690 520 1716 520 1690 520 1690 520 1716 520 1690 520 572 520 598 520 598 520 572 520 572 520 1716 520 572 520 572 520 1716 520 1690 520 1690 520 1716 520 1690 520 572 520 1716 520 43836 8788 2288 520 97344 8788 2288 494 97318</button>
<button label="|&lt;&lt;" labelSize="12.0">8736 4498 494 1690 520 572 520 572 520 572 520 598 494 572 520 572 520 572 520 572 520 1690 520 1664 520 1690 520 1664 520 1690 520 1664 520 1690 520 572 520 1690 520 572 520 572 520 572 520 572 520 1690 520 572 520 1690 520 572 520 1664 520 1690 520 1664 520 1690 520 572 520 1690 520 43264 8762 2262 520 96096 8736 2262 520 96096</button>
<button label="&gt;&gt;|" labelSize="12.0">8736 4498 494 1690 520 572 520 572 520 572 520 598 494 572 520 572 520 572 520 572 520 1690 520 1664 520 1690 520 1664 520 1690 520 1690 494 1664 520 1690 520 1664 520 572 520 598 520 572 520 572 520 1690 468 572 520 572 520 572 520 1690 520 1664 520 1690 520 1664 520 572 520 1690 520 43290 8736 2262 494 96096 8788 2262 520 96096</button>
<button label="input" labelSize="12.0">8762 4524 520 1690 520 598 520 598 520 572 520 572 520 598 520 572 520 572 520 598 520 1690 520 1690 520 1716 520 1690 520 1716 520 1690 520 1690 520 598 494 572 520 598 520 1716 494 1690 520 598 520 1690 520 572 520 1716 520 1690 520 1690 520 598 520 572 520 1690 520 598 520 1690 520 43836 8788 2288 520 97266 8814 2288 520 97266
</button>
<button label="mode" labelSize="12.0">8710 4498 494 1690 520 572 520 572 520 572 520 572 520 598 520 572 520 572 520 572 520 1690 520 1664 520 1690 520 1664 520 1690 520 1664 520 1690 520 1664 520 572 520 598 520 1664 520 1690 520 572 520 1664 520 598 494 572 520 1664 520 1690 520 572 520 572 520 1690 494 572 520 1664 520 43290 8762 2262 520 96096 8762 2262 494 96070</button>
<button label="L" labelSize="12.0">8762 4498 494 1664 520 598 520 572 520 572 520 572 520 572 520 572 520 572 520 598 520 1664 520 1690 494 1664 520 1690 468 1664 520 1690 494 1664 520 572 520 1690 520 572 520 572 520 1664 520 598 442 598 520 572 520 1664 520 572 520 1690 520 1664 520 598 494 1664 520 1664 520 1690 520 43212 8788 2236 520 95992 8788 2262 520 95966</button>
<button label="R" labelSize="12.0">8762 4524 520 1690 520 572 520 598 520 572 520 572 520 598 520 598 520 572 520 572 520 1716 520 1690 520 1690 520 1716 520 1690 520 1716 520 1690 520 1690 520 1716 520 572 520 572 520 1716 520 572 520 572 520 598 520 598 520 572 520 1690 520 1716 520 572 520 1690 520 1716 520 1690 520 43836 8814 2288 520 97318 8814 2288 520 97318</button>
<button label="vol+" labelSize="12.0">8762 4524 520 1690 520 598 520 598 520 572 520 572 520 598 520 572 520 572 520 598 520 1690 520 1690 520 1716 520 1690 520 1716 520 1690 520 1690 520 598 520 572 520 572 520 598 520 1690 520 572 520 598 520 572 520 1690 520 1716 520 1690 520 1716 520 572 520 1690 520 1716 520 1690 520 43836 8788 2262 520 97266 8788 2288 520 97266</button>
<button label="vol-" labelSize="12.0">9099 4698 540 1755 540 594 540 621 540 621 513 594 540 594 540 621 540 594 540 594 540 1782 540 1755 540 1755 540 1782 540 1755 540 1782 540 1755 540 1755 540 621 540 594 540 594 540 1782 540 621 513 594 540 594 540 621 540 1755 540 1755 540 1755 540 594 540 1782 540 1755 540 1755 540 45522 9153 2376 540 101061 9153 2376 540 101061</button>
<button label="reset" labelSize="12.0">8762 4602 494 1716 520 572 520 598 520 598 520 598 520 572 520 598 520 598 520 598 520 1716 520 1742 520 1716 520 1716 520 1716 520 1742 520 1716 520 598 520 1716 520 1716 520 1716 520 598 520 572 520 598 520 598 520 1742 520 598 520 598 520 572 520 1716 520 1716 520 1716 520 1716 520 44408 8788 2314 520 98592 8788 2314 520 98566</button>
<button label="step+" labelSize="12.0">8762 4524 520 1690 520 572 520 598 520 572 520 572 520 598 520 598 520 572 520 572 520 1716 520 1690 520 1690 520 1716 494 1690 520 1716 520 1690 520 1690 520 598 520 1690 520 1690 520 1716 494 572 520 598 520 598 520 572 520 1690 520 598 520 572 520 572 520 1716 520 1690 520 1690 520 43810 8788 2288 520 97292 8788 2288 520 97292</button>
<button label="step-" labelSize="12.0">8736 4498 494 1690 520 572 520 572 520 572 520 572 520 572 520 598 468 572 520 572 520 1664 520 1690 520 1664 520 1690 520 1664 520 1690 520 1664 520 598 520 572 520 1664 520 572 520 1690 520 572 520 572 520 572 520 1690 520 1664 520 598 520 1664 520 572 520 1690 520 1664 520 1690 520 43238 8684 2236 520 96044 8762 2236 520 96070</button>
<button label="c.delay+" labelSize="12.0">8710 4498 494 1690 494 572 520 572 520 572 520 572 520 572 520 598 468 572 520 572 520 1664 520 1690 520 1664 520 1690 520 1664 520 1690 520 1664 520 598 494 572 520 1664 520 1690 520 572 520 572 520 1690 520 572 520 1664 520 1690 520 572 520 572 520 1690 468 1664 520 572 520 1690 520 43238 8788 2236 520 96044 8736 2236 520 96044</button>
<button label="c.delay-" labelSize="12.0">8762 4524 520 1690 520 598 520 598 494 572 520 598 520 598 520 572 520 572 520 598 520 1690 520 1690 520 1690 520 1690 520 1716 520 1690 520 1716 520 572 520 572 520 598 520 598 520 1690 520 598 520 1690 520 572 520 1716 520 1690 520 1716 520 1690 520 572 520 1716 520 572 520 1690 520 43810 8788 2288 520 97266 8788 2288 520 97240</button>
<button label="s.delay+" labelSize="12.0">8762 4524 520 1690 520 598 520 598 520 572 520 572 520 598 520 572 520 572 520 598 520 1690 520 1690 520 1716 520 1690 520 1690 520 1690 520 1690 520 1716 520 572 520 1690 520 1716 520 572 520 572 520 1716 520 572 520 572 520 1716 520 572 520 572 520 1716 520 1690 520 572 520 1716 520 43810 8814 2288 520 97318</button>
<button label="s.delay-" labelSize="12.0">8736 4498 494 1690 520 572 520 572 520 572 520 572 520 572 520 598 494 572 520 572 520 1664 520 1690 520 1664 520 1690 520 1664 520 1690 520 1690 468 1664 520 572 520 572 520 598 468 1664 520 572 520 1690 520 572 520 572 520 1690 468 1664 520 1690 520 572 520 1664 520 572 520 1690 520 43264 8788 2262 494 96070 8736 2236 520 96070</button>
<button label="test on" labelSize="12.0">8736 4498 494 1664 520 598 520 572 520 572 520 572 520 572 520 572 520 598 468 572 520 1664 520 1690 520 1664 520 1690 520 1664 520 1690 520 1664 520 572 520 1690 520 1664 520 1690 520 572 520 572 520 1690 468 572 520 1664 520 572 520 598 468 572 520 1664 520 1690 520 572 520 1664 520 43264 8762 2236 520 96044 8762 2262 520 96018</button>
<button label="test off" labelSize="12.0">8736 4498 494 1664 520 598 468 572 520 572 520 572 520 572 520 572 520 572 520 598 468 1664 520 1664 520 1690 520 1664 520 1690 520 1664 520 1690 520 572 520 1664 520 598 520 572 520 1664 520 572 520 1690 520 572 520 1664 520 598 520 1664 520 1690 468 572 520 1664 520 572 520 1690 520 43238 8736 2236 520 96018 8788 2262 494 95992</button>
<button label="night on" labelSize="12.0">8788 4524 494 1716 520 572 520 572 520 598 520 598 520 572 520 572 520 598 520 572 520 1690 520 1716 520 1690 520 1716 520 1690 520 1690 520 1716 520 1690 520 1690 520 1716 494 1690 520 598 520 598 520 1690 520 598 520 598 520 572 520 572 520 598 520 1690 520 1690 520 598 520 1690 520 43810 8814 2288 520 97318 8814 2288 520 97318</button>
<button label="night off" labelSize="12.0">8710 4498 494 1690 520 572 520 572 520 572 520 572 520 572 520 598 494 572 520 572 520 1664 520 1690 520 1664 520 1690 520 1664 520 1690 520 1664 520 1690 520 1664 520 598 520 572 520 1664 520 572 520 1690 520 572 520 572 520 572 520 1690 520 1664 520 598 520 1664 520 572 520 1690 520 43264 8788 2262 520 96070 8788 2262 520 96044</button>
<button label="status" labelSize="12.0">8684 4420 520 1638 520 572 520 572 494 572 520 572 520 546 520 572 520 572 520 546 520 1664 520 1638 520 1664 520 1638 520 1664 494 1664 520 1664 494 572 520 572 520 572 494 1664 520 572 494 572 520 1664 520 546 520 1664 520 1638 520 1664 520 546 520 1664 520 1638 520 572 520 1638 520 42744 8684 2236 494 94874 8684 2210 520 94874</button>
<button label="listen" labelSize="12.0">8710 4498 494 1690 520 572 520 572 520 572 520 572 520 598 494 572 520 572 520 572 520 1690 494 1664 520 1690 494 1664 520 1690 520 1664 520 1690 520 1664 520 572 520 572 520 1690 520 572 520 572 520 1690 520 572 520 572 520 1690 520 1664 520 572 520 1690 520 1664 520 598 468 1664 520 43264 8788 2236 494 96070 8762 2262 520 96044</button>
<button label="optical" labelSize="12.0">8788 4524 494 1716 520 572 520 572 520 598 520 598 494 572 520 572 520 598 520 572 520 1690 520 1716 520 1690 520 1716 520 1690 520 1690 520 1690 520 572 520 1716 520 572 520 1690 520 598 520 572 520 1690 520 598 520 1690 520 572 520 1716 520 572 520 1690 520 1716 520 572 520 1690 520 43836 8788 2288 520 97266 8814 2288 520 97292</button>
<button label="coax" labelSize="12.0">8736 4498 494 1690 520 572 520 572 520 572 520 572 520 598 468 572 520 572 520 572 520 1690 468 1690 520 1690 468 1664 520 1690 468 1664 520 1690 494 1664 520 1690 520 572 520 1664 520 572 520 598 494 1664 520 572 520 572 520 598 468 1664 520 572 520 1690 520 1664 520 572 520 1690 520 43264 8710 2236 520 96070 8788 2236 520 96070</button>
<button label="mem" labelSize="12.0">8658 4420 520 1638 520 572 520 572 494 572 520 572 520 546 520 572 520 572 520 546 520 1664 520 1638 520 1664 520 1638 520 1664 468 1664 520 1664 468 572 520 1664 468 1664 520 1664 494 1664 520 572 520 546 520 572 520 1638 520 572 520 572 520 546 520 572 520 1638 520 1664 520 1638 520 42718 8684 2210 520 94822 8736 2210 520 94822</button>
<button label="am" labelSize="12.0">8736 4498 494 1690 494 572 520 572 520 572 520 572 520 572 520 598 468 572 520 572 520 1664 520 1690 520 1664 520 1690 520 1664 520 1690 520 1664 520 1690 520 572 520 572 520 1690 520 572 520 572 520 572 520 572 520 572 520 1690 520 1664 520 598 494 1664 520 1690 520 1664 520 1690 520 43264 8762 2262 520 96044 8788 2262 468 96044</button>
<button label="fm" labelSize="12.0">8736 4498 494 1690 520 572 520 572 520 572 520 572 520 598 494 572 520 572 520 572 520 1664 520 1690 520 1690 494 1664 520 1690 494 1664 520 1690 520 1664 520 572 520 1690 520 572 520 1664 520 598 520 572 520 572 520 572 520 1690 494 572 520 1664 520 572 520 1690 520 1664 520 1690 520 43264 8736 2236 520 96070 8736 2236 520 96070</button>
<button label="scan+" labelSize="12.0">8762 4602 494 1716 520 598 520 572 520 598 520 598 520 598 520 572 520 598 520 598 520 1742 494 1716 520 1716 520 1742 494 1716 520 1716 520 1716 520 1716 520 1716 520 1742 494 1716 520 1716 520 598 520 572 520 598 520 598 520 598 520 572 520 598 520 598 520 1716 520 1716 520 1716 520 44382 8788 2314 520 98514 8814 2288 520 98514</button>
<button label="scan-" labelSize="12.0">8762 4602 494 1716 520 598 520 572 520 598 520 598 520 572 520 598 520 598 520 598 520 1716 520 1716 520 1716 520 1716 520 1742 520 1716 520 1716 520 572 520 598 520 1716 520 1716 520 1742 520 598 520 598 520 598 494 1716 520 1716 520 598 520 572 520 598 520 1716 520 1716 520 1716 520 44408 8788 2314 520 98566 8788 2314 520 98540</button>
<button label="stereo" labelSize="12.0">8762 4524 520 1690 520 598 520 598 520 572 520 572 520 598 520 572 520 572 520 598 520 1690 520 1690 520 1716 520 1690 520 1716 520 1690 520 1690 520 598 520 1690 520 1690 520 598 520 1690 520 598 520 598 520 572 520 1690 520 598 520 572 520 1690 520 598 520 1690 520 1716 520 1690 520 43810 8788 2262 520 97266 8814 2288 520 97292</button>
<button label="mono" labelSize="12.0">8788 4524 494 1716 520 572 520 572 520 598 520 572 520 572 520 598 520 598 494 572 520 1716 520 1690 520 1690 520 1716 520 1690 520 1716 520 1690 520 1690 520 1690 520 1690 520 598 520 1690 520 572 520 598 520 572 520 572 520 598 520 598 520 1690 520 598 520 1690 520 1690 520 1716 520 43810 8788 2288 520 97292 8788 2288 520 97292</button>
<button label="cen+" labelSize="12.0">8762 4550 494 1716 494 572 520 598 520 598 494 572 520 598 520 598 494 572 520 598 520 1690 520 1690 520 1690 520 1690 520 1690 520 1690 520 1690 520 572 520 1716 520 572 520 1690 520 1690 520 572 520 598 520 572 520 1690 520 572 520 1690 520 598 520 572 520 1690 520 1690 520 1690 520 43784 8788 2288 520 97214 8788 2288 520 97214</button>
<button label="cen-" labelSize="12.0">8762 4550 494 1716 494 572 520 598 520 598 494 572 520 598 520 598 494 572 520 598 520 1690 520 1690 520 1690 520 1690 520 1690 520 1690 520 1690 520 1690 520 572 520 572 520 1716 520 1690 520 598 520 572 520 572 520 598 520 1690 520 1716 520 572 520 572 520 1716 494 1690 520 1716 494 43758 8814 2288 520 97188 8814 2262 520 97188</button>
<button label="sw+" labelSize="12.0">8762 4550 494 1716 494 572 520 598 520 572 520 572 520 598 520 572 520 572 520 598 520 1690 520 1690 520 1690 520 1690 520 1690 520 1690 520 1690 520 1690 520 1690 520 572 520 1690 520 1690 520 598 520 572 520 572 520 598 520 572 520 1690 520 598 494 572 520 1716 520 1690 520 1716 520 43758 8814 2288 520 97188 8788 2262 520 97188</button>
<button label="sw-" labelSize="12.0">8762 4576 520 1716 520 572 520 598 520 598 520 598 520 572 520 598 520 598 520 598 520 1742 520 1716 520 1716 520 1716 520 1716 520 1742 494 1716 520 572 520 598 520 598 520 1716 520 1716 520 598 520 572 520 598 520 1716 520 1716 520 1716 520 598 520 598 520 1716 520 1716 520 1742 520 44330 8788 2288 520 98410 8814 2314 520 98436</button>
<button label="sl+" labelSize="12.0">8762 4550 494 1690 520 572 520 598 520 572 520 572 520 598 520 572 520 572 520 598 520 1690 520 1716 520 1690 520 1716 520 1690 520 1716 520 1690 520 598 520 572 520 1690 520 598 520 1690 520 598 520 1690 520 598 520 1690 520 1690 520 598 520 1690 520 598 520 1690 520 598 520 1690 520 43732 8788 2288 520 97162 8814 2262 520 97136</button>
<button label="sl-" labelSize="12.0">8762 4524 520 1690 520 572 520 598 520 572 520 572 520 598 520 572 520 572 520 598 520 1690 520 1716 520 1690 520 1716 520 1690 520 1716 494 1690 520 1716 494 572 520 1716 520 572 520 1690 520 572 520 1690 520 598 520 572 520 1716 520 572 520 1690 520 598 520 1690 520 598 520 1690 520 43758 8814 2288 494 97136 8814 2288 494 97162</button>
<button label="sr-" labelSize="12.0">8762 4550 494 1716 520 572 520 572 520 598 520 572 520 572 520 598 520 572 520 572 520 1716 520 1690 520 1716 520 1690 520 1716 520 1690 520 1716 520 572 520 1690 520 1690 520 572 520 1716 520 572 520 1690 520 598 494 1690 520 598 520 572 520 1690 520 598 520 1690 520 598 520 1690 520 43758 8814 2288 520 97214 8788 2262 520 97214</button>
<button label="sr+" labelSize="12.0">8788 4524 520 1690 520 598 520 572 520 572 520 598 520 572 520 572 520 598 520 572 520 1690 520 1690 520 1690 520 1690 520 1690 520 1690 520 1690 520 1690 520 1690 520 1690 520 572 520 1716 520 572 520 1716 520 572 520 572 520 598 520 572 520 1690 520 598 520 1690 520 598 520 1690 520 43784 8788 2262 520 97188 8788 2288 520 97188</button>
</device>
</irplus>

**Comment by irplus-remote** [comment]
@SingularityB  Could you please test them? (Rename file to *.irplus)
