### ISSUE TITLE
Sat-One Easy-One T7 DVB-T

### ISSUE THREAD

**Issue by ch3w133d** [irplus-remote/irplus-codes.github.io#289]
Missing entry for that model of digital terrestrial recevier. On manufacturer's site i found the IR codes: 4850, 4867. Is it possible update the list? Thanks for your time, great app

**Comment by irplus-remote** [comment]
Hi will try to add. Note that any 4 letter "codes" are only referals for embedded code dbs of hardware universal remotes. I cant do anything with them. To create a remote layout the real bits of each button are needed ;)

Of the other setone/easyone. Is there a layout which works (partly?)

**Comment by ch3w133d** [comment]
I'm totally newbie. I've tinkered a lot and i found other brands working on ''codes'' 4850,4867. For example GBC have the same format WINLIRC_NEC1 and works for few buttons. So i copy and paste the working buttons and made a new layout. My question is: can you tell me how understand the hex-codes for completing the number-pad? I've tried figure out with no success. I attach the xml file of the working buttons.
[Easy-One_T7.zip](https://github.com/irplus-remote/irplus-codes.github.io/files/697159/Easy-One_T7.zip)
Thanks for the support
[the numbers with no codes are the ones that i would find]

**Comment by irplus-remote** [comment]
Hi, could you try the following codes from the internal db. They share the same device-id so you may be able to "frankenstein" the missing codes from them:

DENVER - MCD
XORO - HRK8750
(maybe best match for numbers): MPMAN DVB-T2012 V2 (not 1!)

**Comment by irplus-remote** [comment]
Id be happy if you share the full file after checkingt he codes

**Comment by irplus-remote** [comment]
<irplus>
    <device manufacturer="SETONE" model="Easyone T7" columns="12" format="WINLIRC_NEC1" bits="16" pre-bits="16">

        <button label="&#xf011;" alt="POWER" backgroundColor="FFC84334" span="4">0x00ff 0xea15</button>
        <space multiple="4"/>
        <button label="Mute" span="4">0x00ff 0xfa05</button>1

        <button label="1" span="4">0x00ff 0xda25</button>
        <button label="2" span="4">0x00ff 0xf20d</button>
        <button label="3" span="4">0x00ff 0xca35</button>

        <button label="4" span="4">0x00ff 0x5aa5</button>
        <button label="5" span="4">0x00ff 0xf00f</button>
        <button label="6" span="4">0x00ff 0x7a85</button>

        <button label="7" span="4">0x00ff 0x6a95</button>
        <button label="8" span="4">0x00ff 0x728d</button>
        <button label="9" span="4">0x00ff 0x4ab5</button>

        <button label="TV" span="4">0x00ff 0x9867</button>
        <button label="0" labelSize="25.0" span="4">0x00ff 0xaa55</button>
        <button label="LAST" labelSize="12.0" span="4">0x00ff 0xf807</button>

        <button label="Menu" span="4">0x00ff 0x58a7</button>
        <button label="&#xf0d8; CH" span="4">0x00ff 0x708f</button>
        <button label="Exit" span="4">0x00ff 0xe817</button>

        <button label="&#xf0d9; VOL" span="4">0x00ff 0x6897</button>
        <button label="OK" span="4">0x00ff 0x48b7</button>
        <button label="VOL &#xf0da;" span="4">0x00ff 0x7887</button>

        <space multiple="4"/>
        <button label="&#xf0d7; CH" span="4">0x00ff 0x28d7</button>
        <space multiple="4"/>

        <space multiple="3"/>
        <space multiple="3"/>
        <button label="epg" labelSize="12.0" span="3">0x00ff 0x32cd</button>
        <button label="fav" labelSize="18.0" span="3">0x00ff 0x0af5</button>

        <button label="R" fillColor="FFC84334" span="3">0x00ff 0x18e7</button>
        <button label="G" fillColor="FF1E7854" span="3">0x00ff 0x08f7</button>
        <button label="Y" fillColor="FFD6A81F" span="3">0x00ff 0x38c7</button>
        <button label="B" fillColor="FF2A4C94" span="3">0x00ff 0x8877</button>

        <button label="info" labelSize="18.0" span="3">0x00ff 0x1ae5</button>
        <space multiple="3"/>
        <button label="subs" labelSize="18.0" span="3">0x00ff 0x2ad5</button>
        <space multiple="3"/>

    </device>
</irplus>

**Comment by irplus-remote** [comment]
Please try - still some buttons missing though :/
