### ISSUE TITLE
Evo Enfinity Combo X

### ISSUE THREAD

**Issue by irplus-remote** [irplus-remote/irplus-codes.github.io#291]

**Comment by Amelichev** [comment]
Hello! Do you mean this remote?
![a2895c296d_brsqfx](https://cloud.githubusercontent.com/assets/25001954/22065395/21f8bd00-dd99-11e6-9b0c-6fe89a74f4b2.jpg)

**Comment by Amelichev** [comment]
If yes - here the codes:
"EVO Enfinity XCombo+" have the same remote control with "openbox sx4hd"

**Comment by irplus-remote** [comment]
Thanks! 👍
