### ISSUE TITLE
AEG BSS 4814 Soundbar

### ISSUE THREAD

**Issue by irplus-remote** [irplus-remote/irplus-codes.github.io#294]
https://irplus-remote.github.io/?start=codes#codes

**Comment by Amelichev** [comment]
Here the RAW codes - compared with original, all buttons have right signal.
[aeg.txt](https://github.com/irplus-remote/irplus-codes.github.io/files/722808/aeg.txt)

**Comment by irplus-remote** [comment]
Thanks 👍  Added.
