### ISSUE TITLE
Livarno LED bulb code (LIDL)

### ISSUE THREAD

**Issue by scrax** [irplus-remote/irplus-codes.github.io#298]
Hi, I've made this for a led light.
It's a lamp bought at LIDL 
LIVARNOLUX
Model Nr: HG00197
Version: 09/2015

[LIVARNO - LED COLOUR EFFECT LAMP.irplus.zip](https://github.com/irplus-remote/irplus-codes.github.io/files/730367/LIVARNO.-.LED.COLOUR.EFFECT.LAMP.irplus.zip)

**Comment by irplus-remote** [comment]
Hi Thanks! 👍 Will be added soon

**Comment by scrax** [comment]
Thank's to you for your great app. Submitting codes is "mandatory" IMHO to give back a little help to your big work
