### ISSUE TITLE
GRUNDIG Vision6 TV codes

### ISSUE THREAD

**Issue by scrax** [irplus-remote/irplus-codes.github.io#299]
This is for a Vision6 TV.
Made by mixing buttons from other codes
[GRUNDIG - Vision 6.irplus.zip](https://github.com/irplus-remote/irplus-codes.github.io/files/730394/GRUNDIG.-.Vision.6.irplus.zip)

**Comment by irplus-remote** [comment]
Will be included in next build, sorry missed this issue
