### ISSUE TITLE
Sony VPL Projector

### ISSUE THREAD

**Issue by prcvilla** [irplus-remote/irplus-codes.github.io#302]
Just got a VPL ES4 projetor to turn on and off.
Couldn't make it toogle on/off with one button.
Site: http://www.remotecentral.com/cgi-bin/mboard/rc-discrete/thread.cgi?7294

`
<irplus>
<device manufacturer="Sony" model="Projector" columns="3" format="PRONTO_HEX" frequency="40638" scaleRatio="3.0">
<button label="On" labelSize="20.0" labelColor="FF000000" backgroundColor="FFFFFFFF">0000 0066 0030 0000 005f 0018 0019 0018 0030 0018 0030 0018 0030 0018 0019 0018 0030 0018 0019 0018 0019 0018 0019 0018 0030 0018 0019 0018 0030 0018 0019 0018 0030 0018 0019 0335 005f 0018 0019 0018 0030 0018 0030 0018 0030 0018 0019 0018 0030 0018 0019 0018 0019 0018 0019 0018 0030 0018 0019 0018 0030 0018 0019 0018 0030 0018 0019 0335 005f 0018 0019 0018 0030 0018 0030 0018 0030 0018 0019 0018 0030 0018 0019 0018 0019 0018 0019 0018 0030 0018 0019 0018 0030 0018 0019 0018 0030 0018 0019 0018</button>
<button label="Off" labelSize="20.0" labelColor="FF000000" backgroundColor="FFFFFFFF">0000 0066 0030 0000 005f 0018 0030 0018 0030 0018 0030 0018 0030 0018 0019 0018 0030 0018 0019 0018 0019 0018 0019 0018 0030 0018 0019 0018 0030 0018 0019 0018 0030 0018 0019 031e 005f 0018 0030 0018 0030 0018 0030 0018 0030 0018 0019 0018 0030 0018 0019 0018 0019 0018 0019 0018 0030 0018 0019 0018 0030 0018 0019 0018 0030 0018 0019 031e 005f 0018 0030 0018 0030 0018 0030 0018 0030 0018 0019 0018 0030 0018 0019 0018 0019 0018 0019 0018 0030 0018 0019 0018 0030 0018 0019 0018 0030 0018 0019 0018</button>
</device>
</irplus>
`

**Comment by irplus-remote** [comment]
Hi, what smartphone did you use for testing ? The code seems ok :/

**Comment by prcvilla** [comment]
I'm using my LG G3 (D855) and it work almost flawlessly for this projector.

**Comment by irplus-remote** [comment]
So i can close this issue? Didn't understand if you still need some help with getting it to work with irplus or not? :) If yes what did go wrong? Which codeset are you using now?

**Comment by prcvilla** [comment]
I couldn't find this projector in the code set available, I thought it was a way to share the codes to other. Anyways, it's fine, there is no issue and it can be closed.

**Comment by irplus-remote** [comment]
Ah ok i understand! will add it to the next version. Thanks!
