### ISSUE TITLE
LG - MKJ39170828 

### ISSUE THREAD

**Issue by molafir** [irplus-remote/irplus-codes.github.io#308]
please add remote control - MKJ39170828  codes
![df1c40de-0051-11e7-9038-793b787296f6](https://cloud.githubusercontent.com/assets/12770700/23962013/00166188-09c2-11e7-835d-3769569e405b.jpg)

**Comment by irplus-remote** [comment]
Hi, which code did not work? From LG Generic TV?

**Comment by molafir** [comment]
hex code

**Comment by irplus-remote** [comment]
whole sentence please. As said the LG generic codefile should work. If there is something wrong please explain in whole intelligible sentences. Thanks
