### ISSUE TITLE
[irplus LAN] Android widgets not working

### ISSUE THREAD

**Issue by marcsima79** [irplus-remote/irplus-codes.github.io#309]
Widgets reports network error
Inapp irplusLan workes fine

Android 7.11
LineageOs

**Comment by irplus-remote** [comment]
Hi, could you provide more details? Can't imagine why Widgets should report network errors. Could you try to make a video or screenshot? Maybe even try to uninstall the app and reinstall it from Playstore?

**Comment by marcsima79** [comment]
Hi,
[https://youtu.be/yIfzDswOa24](url)
hope i made somthing wrong.
Best regards

**Comment by marcsima79** [comment]
Now i tested on another device.
Xperia z3c Android 6.0.1 same problem.

**Comment by irplus-remote** [comment]
I have identified the problem, my bad :) Will try to find a solution and post a new apk here so you can test and give feedback. 

By the way, did you have any problems setting up the python server or was the guide ok?

**Comment by irplus-remote** [comment]
Could you please test?:

https://drive.google.com/file/d/0B3BPAmebhawpZEdhZmVYaGFPS2s/view?usp=sharing

**Comment by marcsima79** [comment]
Hi,
tested and its working. In the next days i will setup for daily use, give you further feedback and 5 stars in playstore.  Thanks for the quick fix.
