### ISSUE TITLE
Panasonic TX-L32C4E

### ISSUE THREAD

**Issue by Laifisnau** [irplus-remote/irplus-codes.github.io#310]
using tx-tv serie as setting (in The software) The TV Not start pressing on-off burton. .But The remote (in The software ) working when The TV is turned on (using  The original Panasonic remote)

**Comment by irplus-remote** [comment]
Hi, try N2QAYB000239 please - should work, as this one repeats the power signal like the real remote

**Comment by Laifisnau** [comment]
It works But del volume up &down do 3 step instead ine (v+++ instead v+)But is Not a problem.
