### ISSUE TITLE
Panasonic radio cd mp3 sc-hc17

### ISSUE THREAD

**Issue by Laifisnau** [irplus-remote/irplus-codes.github.io#311]
hello

its possibile add command For The device? 

i've try using sc-htb series But work only 2 or 3 command (mute But Not work on off funziona ect )

tank you

**Comment by irplus-remote** [comment]
Hi, could you try some others too? 

SA-HT, SA-AK, RAK-***, SC-PM

Maybe you can find all codes there, if they are in different files , i can create a new layout with codes taken from there , but i need to know whoch one works

Status for now:

So you say MUTE from SC-HTB works 
MUTE - (protocol = Panasonic, device = 160, subdevice = 0, obc = 50)

**Comment by Amelichev** [comment]
Remote control Number: N2QAYC000060
Codes: 
[panas.irplus.txt](https://github.com/irplus-remote/irplus-codes.github.io/files/889675/panas.irplus.txt)

**Comment by Laifisnau** [comment]
sorry 4 my english but... how can i import the file txt in the app????? @_@

**Comment by irplus-remote** [comment]
Hi, the correct ending would be *.irplus (just rename it) then you can click it and it should auto-open with the app

**Comment by Laifisnau** [comment]
i've try The radio  with the attacched code...

turn on- works cd-radio selection ok(But i havn't try usb) work volume +- and mute selection!

Perfect!  
tank you community!

**Comment by Amelichev** [comment]
irplus-remote, I think you can add this codes to your base, I'm sure they are right.
