### ISSUE TITLE
Assigning Pronto Hex codes to a button?

### ISSUE THREAD

**Issue by tomb18** [irplus-remote/irplus-codes.github.io#314]
Hi,
I don't know where to ask this so I am trying here.
I have installed irplus on a tab 5 tablet and have it working with my LG TV.  All the functions work except I would like to edit some buttons to add discrete Power On and Off.  These codes (pronto hex codes I think) are available on remote central.  However, I have not found out how to actually edit a button in irplus to provide these codes.  Is there a place where this is explained? Or how do I do it?  I tried entering all the codes manually and it did not work.
Thanks

**Comment by irplus-remote** [comment]
Hi can you link or post the codes you want to add?

**Comment by tomb18** [comment]
HiThanks so much! Here is the link
http://www.remotecentral.com/cgi-bin/mboard/rc-discrete/thread.cgi?7244
I only need the power on, power off and the HDMI inputs. 
Thanks

Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: irplus-remote <notifications@github.com> Date: 2017-04-07  1:19 PM  (GMT-05:00) To: "irplus-remote/irplus-codes.github.io" <irplus-codes.github.io@noreply.github.com> Cc: tomb18 <tomb18@videotron.ca>, Author <author@noreply.github.com> Subject: Re: [irplus-remote/irplus-codes.github.io] Assigning Pronto Hex codes to a button? (#314) 
Hi can you link or post the codes you want to add?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/irplus-remote/irplus-codes.github.io","title":"irplus-remote/irplus-codes.github.io","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/irplus-remote/irplus-codes.github.io"}},"updates":{"snippets":[{"icon":"PERSON","message":"@irplus-remote in #314: Hi can you link or post the codes you want to add?"}],"action":{"name":"View Issue","url":"https://github.com/irplus-remote/irplus-codes.github.io/issues/314#issuecomment-292597984"}}}

**Comment by irplus-remote** [comment]
Ok use the TV - LG Generic file and use this codes:

P_on:  0x20DF 0x23DC
P_off:  0x20DF 0xA35C

hdmi1: 0x20DF 0x738C
hdmi2: 0x20DF 0x33CC
hdmi3: 0x20DF 0x9768

**Comment by tomb18** [comment]
HiThank you so much for this. Very appreciated. Best regards, Tom


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: irplus-remote <notifications@github.com> Date: 2017-04-07  3:20 PM  (GMT-05:00) To: "irplus-remote/irplus-codes.github.io" <irplus-codes.github.io@noreply.github.com> Cc: tomb18 <tomb18@videotron.ca>, Author <author@noreply.github.com> Subject: Re: [irplus-remote/irplus-codes.github.io] Assigning Pronto Hex codes to a button? (#314) 
Ok use the TV - LG Generic file and use this codes:
P_on:  0x20DF 0x23DC

P_off:  0x20DF 0xA35C
hdmi1: 0x20DF 0x738C

hdmi2: 0x20DF 0x33CC

hdmi3: 0x20DF 0x9768

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/irplus-remote/irplus-codes.github.io","title":"irplus-remote/irplus-codes.github.io","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/irplus-remote/irplus-codes.github.io"}},"updates":{"snippets":[{"icon":"PERSON","message":"@irplus-remote in #314: Ok use the TV - LG Generic file and use this codes:\r\n\r\nP_on:  0x20DF 0x23DC\r\nP_off:  0x20DF 0xA35C\r\n\r\nhdmi1: 0x20DF 0x738C\r\nhdmi2: 0x20DF 0x33CC\r\nhdmi3: 0x20DF 0x9768"}],"action":{"name":"View Issue","url":"https://github.com/irplus-remote/irplus-codes.github.io/issues/314#issuecomment-292628530"}}}
