### ISSUE TITLE
Samsung CXD1932

### ISSUE THREAD

**Issue by bennykaganovich** [irplus-remote/irplus-codes.github.io#315]
Support for this TV from 1996?

**Comment by irplus-remote** [comment]
Hi, did you try the available samsung codes? Which Smartphone?

**Comment by irplus-remote** [comment]
I'm closing as there was no answer to the question. (So i just guess some codes are indeed working ;-) If not feel free to reanswer with more detailled information

- Did you _really_ try all other Samsung TV codes?
- What smartphone are you using?
- Saw any errors?
