### ISSUE TITLE
Genius SW-HF5.1 5000 audio device (working config)

### ISSUE THREAD

**Issue by b0rek** [irplus-remote/irplus-codes.github.io#316]
Hi, 
Thanks for great soft! Thanks to it I've managed to create 'virtual pilot' to my speakers.
Config files for irplus and lirc attached. Add them to next version, please.

[Genius SW-HF5.1 5000.irplus.txt](https://github.com/irplus-remote/irplus-codes.github.io/files/908691/Genius.SW-HF5.1.5000.irplus.txt)
[Genius SW-HF5.1 5000.lirc.txt](https://github.com/irplus-remote/irplus-codes.github.io/files/908697/Genius.SW-HF5.1.5000.lirc.txt)

**Comment by irplus-remote** [comment]
Cleaning up some issues. This code is added under "SW-HF5.1 5000 V2" as the other 5000 Series had different codes. So i added them both.
