### ISSUE TITLE
LED RGB strip 24key China no name (working config) 

### ISSUE THREAD

**Issue by b0rek** [irplus-remote/irplus-codes.github.io#317]
Hi, 
configs for irplus and lirc for no name 24 key RGB LED strip remote. You can add it to next release.
Cheers!

[LED RGB 24key LB.irplus.txt](https://github.com/irplus-remote/irplus-codes.github.io/files/908706/LED.RGB.24key.LB.irplus.txt)
[LED RGB 24key LB.lirc.txt](https://github.com/irplus-remote/irplus-codes.github.io/files/908707/LED.RGB.24key.LB.lirc.txt)

**Comment by barney222** [comment]
hello not. working for my strip why? 17 button controller have i.

**Comment by b0rek** [comment]
There is no standard and there is no way to tell which controller is which. I have couple of controllers but everyone uses different codes.

**Comment by barney222** [comment]
this is my controller https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQc4_yxBn22SK_mUIRE4mpTZXsVQuz4_hdNCGrT6WN3h_C1AAF7Qw

**Comment by irplus-remote** [comment]
Try some other RGB Codes (Choose LED Lights (Group) inside the app. If none of them work, see the guide to capture codes:

https://irplus-remote.github.io/#codes

**Comment by irplus-remote** [comment]
Closing this as the original codes supplied are inside the app.
Under "LILUCO" -> "LED"
or "LED-Lights" -> "Liluco"
Thanks again for posting!
