### ISSUE TITLE
No brand list or device list showing in add device

### ISSUE THREAD

**Issue by Vildkatten** [irplus-remote/irplus-codes.github.io#318]
Using Samsung Galaxy S6 on Android 7.0

**Comment by irplus-remote** [comment]
Hi strange. Since when did this happen? Using latest version? Could you try to reinstall? Check the permissions too maybe.

;(

**Comment by irplus-remote** [comment]
Closing it, since i can't reproduce and no answer. If the problem still persists feel free to re-open
