### ISSUE TITLE
Bauhn ATV50F-415

### ISSUE THREAD

**Issue by CheeseFrog** [irplus-remote/irplus-codes.github.io#322]
Bauhn ATV50F-415 digital TV
[Bauhn ATV50F-415.irplus.zip](https://github.com/irplus-remote/irplus-codes.github.io/files/1097432/Bauhn.ATV50F-415.irplus.zip)

 custom codes, tested, working. Incomplete set but contains essential functions.

**Comment by irplus-remote** [comment]
Thanks, will add this :)

**Comment by CheeseFrog** [comment]
Hey thanks but I don't see it in the list

**Comment by irplus-remote** [comment]
Yeah its not yet inside, will release a new version soon.

**Comment by CheeseFrog** [comment]
Thanks mate
