### ISSUE TITLE
deleyCon HDMI Switcher 5x1

### ISSUE THREAD

**Issue by Outasight** [irplus-remote/irplus-codes.github.io#323]
Hi,
thanks for this great app.

Could you please add support for the deleyCon HDMI Switcher 5x1 (MK108)? You have the 3x1 (MK107), but unfortunately it doesn't work for the 5x1.

Thank you.

**Comment by Amelichev** [comment]
Hello! Try this:
[MK108.irplus.txt](https://github.com/irplus-remote/irplus-codes.github.io/files/1111084/MK108.irplus.txt)

**Comment by Amelichev** [comment]
Here the link for importing: www.clickpdu.ru/files/hex/MK108.irplus

**Comment by irplus-remote** [comment]
Thanks i guess i can close this as Amelichev's codes are always working perfectly  👍

**Comment by Outasight** [comment]
You are awesome. It works perfectly :)

Thank you very much!

**Comment by Jeppa** [comment]
Hi there ,
is the code for the deleyCON 5x1 MK1834 available?
(4K-device)

MK107/MK108 are not working for this device.

**Comment by Amelichev** [comment]
Hi! Try this:
[MK1834.zip](https://github.com/irplus-remote/irplus-codes.github.io/files/3147371/MK1834.zip)

**Comment by Jeppa** [comment]
That's something i can work with ;) Thanx!
