### ISSUE TITLE
Refresh IR-signal duration

### ISSUE THREAD

**Issue by Gustl22** [irplus-remote/irplus-codes.github.io#325]
In this special case of the repetition-codes like they appear in #319,
if you press one button with a longer duration (longer ir-code), all other buttons (with shorter codes) then need the same duration. But the action is performed directly at the beginning. It seems that there's a timeout of that button which needs the longest, you already pressed. Even the buttons of other devices act longer.
After restart of my phone, the timeout duration is refreshed again and it works faster for the normal buttons. It's strange, that closing the app and deleting the cache doesn't encourage the app to recalculate the timeout value.
Try it yourself. 
Hopefully it's not a bug of my phone... I have no other devices to check this.
Thx,
Gustl

**Comment by irplus-remote** [comment]
Hey, is it a galaxy s4?

**Comment by Gustl22** [comment]
No it's a S5 LTE+

**Comment by irplus-remote** [comment]
Maybe it suffers from the same bug, using stock firmware? I remember during my S4 tests there was some weird memory bug where the transmit method of the IR manager would not delete already sent bytes, so on a new command, it would repeat all other codes.

e.g if first you sent    binary 110010101000111110 then only 00001100 it would actually send 000011001000111110 (just a simplified description of it)

I don't have this on my Honor 8 and Honor 9

**Comment by Gustl22** [comment]
Ok, i have the newest Lineage Version installed (14.1). But maybe they haven't forced this probleem. 
But then, every new press would cause a longer timeout (Sum of alle appeared Codes), but i could not detrrmine that. As long as i don't press loong-coded buttons, all works fine. Thx. Maybe i can log the ir-manager, to explore this :)

**Comment by irplus-remote** [comment]
Do you have a dev environment set up? 

Then you could try to transmit both byte arrays (the long code) and then after it a short one , and capture to see if its transmitting the correct one. 

I don't think it can be anything in the app. More likely It's a rom issue

**Comment by Gustl22** [comment]
I never did this before, but i will try some usb-debugging and maybe i get some infos. Unfortunately i cannot record the signals. 
If i get ahead in this topic, i will let u know.
But I'm sure that the correct code is sent immediate, because the receiver reacts directly and then after the timeout the haptic feedback on the smartphone is given. Thanks 4 your help.

**Comment by Gustl22** [comment]
Hey, i build a ir-receiver, so i recorded the signals.
![grafik](https://user-images.githubusercontent.com/18537755/28716708-f417c4e8-739e-11e7-9176-5f576e431195.png)
Maybe you can do something with it.
Here the lirc records, but i think the record does not match the input. In addition a Audacity project.
[Remote Problem Samsung Galaxy S5.zip](https://github.com/irplus-remote/irplus-codes.github.io/files/1182985/Remote.Problem.Samsung.Galaxy.S5.zip)

**Comment by Gustl22** [comment]
I created a test application and tested my device:
https://github.com/Gustl22/InfraredTester
The short code was always short, even after the long code. So the buffer in consumerir-manager was deleted. 
You may use a mechanism for the repetition codes, because zero values aren't accepted for breaks. Maybe the buffer is not deleted in that mechanism.
After the usage of my app, the other buttons in irplus work normal again until I press a "long press" button.
Hope, I was able to help you ;D

**Comment by irplus-remote** [comment]
I'm closing this as im'cleaning up old issues, if you still using the app and S4 still causes issue please recreate a new one. (With used Android version, irplus version , codeset )
