### ISSUE TITLE
JVC GZ-MG130E

### ISSUE THREAD

**Issue by n3oney** [irplus-remote/irplus-codes.github.io#330]
Will this old camera be added?please.

**Comment by Amelichev** [comment]
Hello! Try to import this codes: www.clikpdu.ru/files/hex/RM-V750U.irplus

**Comment by heheszeq** [comment]
This doesnt seem to be working.camera dont react

**Comment by Amelichev** [comment]
Are you sure that your device has IR diode? Can you control TV or DVD with IRPLUS?

**Comment by heheszeq** [comment]
Yeah, i can. Just switched my TV on.

**Comment by irplus-remote** [comment]
some cameras also need an external ir module. does it work with the real camera remote?

**Comment by heheszeq** [comment]
I dont have an remote. Sorry

**Comment by heheszeq** [comment]
But at front of camera i can see something like ir (i will send link)

**Comment by heheszeq** [comment]
https://drive.google.com/file/d/0BwQxQV-x1e4_RVhFY3dMel83VjA/view?usp=drivesdk on the left from lens

**Comment by Amelichev** [comment]
See the manual: https://www.manualslib.com/manual/257648/Jvc-Gz-Mg130e-Ek.html?page=6#manual
Page 6: REMOTE CONTROL UNIT: GZ-MG275/255/155/135
Sorry, I expect your model GZ-MG130 doesn't support IR control.

**Comment by heheszeq** [comment]
But on next page i see this: https://drive.google.com/file/d/0BwQxQV-x1e4_UDBSTlo2bG0wams/view?usp=drivesdk
The model looks exact the same AS my camera.

**Comment by heheszeq** [comment]
So the camera got an ir receiver. Any ideas?

**Comment by irplus-remote** [comment]
You should be able to see it. or make some photo from front view

**Comment by heheszeq** [comment]
I see it. I already send: https://drive.google.com/file/d/0BwQxQV-x1e4_RVhFY3dMel83VjA/view?usp=drivesdk
