### ISSUE TITLE
Panasonic TH-42PV8PA TV power button

### ISSUE THREAD

**Issue by PandeleFlorin** [irplus-remote/irplus-codes.github.io#335]
Hi
I do have Panasonic TH-42PV8PA and a problem with powering it on from this app. The original remote has only one button for power on/off and has to be hold down for a brief period for the TV to turn on. The preset I used is "TV (Plasma) 2003-2007". The phone can operate any other command except power on, and interestingly works perfectly for Power off (so the code is correct). I tried also setting a double IR code on the button (copy-paste) and the app says that the code is not compatible with the IR sender(or similar). I tried also to put the repeat interval to 0 ms with no effect whatsoever. The TV "receive ir/power" led blinks but does not turn on. Any idea ?

**Comment by irplus-remote** [comment]
Hi, tried the codeset. N2QAYB000239 ?

**Comment by PandeleFlorin** [comment]
The "device" I used is "TV (Plasma) 2003-2007". I think i went through all Panasonic "device"s and none managed to start the TV.

**Comment by irplus-remote** [comment]
I think the N2QAY should be able, as the repeat-sequence for the power button has been emulated here.

**Comment by irplus-remote** [comment]
Please retry

**Comment by irplus-remote** [comment]
I guess it can be closed, im pretty sure the N2QAY codes work. If not feel free to anwer.
