### ISSUE TITLE
Can't find code for Philips PT9000

### ISSUE THREAD

**Issue by lrdyupa** [irplus-remote/irplus-codes.github.io#337]
This is the television;
https://www.philips.it/c-p/PT9000_12/tv-portatile

Can you add it to your app?
Thanks in advance!

**Comment by irplus-remote** [comment]
Did you try the standard philips tv codes? They should work

**Comment by irplus-remote** [comment]
I'm closing as there was no answer to the question. (So i just guess some codes are indeed working ;-) If not feel free to reanswer with more detailled information

- Did you _really_ try all philip codes?
- What smartphone are you using?
- Saw any errors?
