### ISSUE TITLE
Cisco ISB2201

### ISSUE THREAD

**Issue by pordog** [irplus-remote/irplus-codes.github.io#338]
Hi!

Can You give the Cisco ISB2201 STB please!

Thanks!
Peter

**Comment by Amelichev** [comment]
Hi! Try this codes: https://clickpdu.ru/files/hex/cisco.irplus

**Comment by Amelichev** [comment]
If it works - I can add other buttons.

**Comment by pordog** [comment]
Hi!

Your codes for Cisco ISB2201 working fine! Every buttons are ok. Can You
send me others buttons?

Thanks!
Peter

2017. okt. 17. 11:48 ezt írta ("Andrey Amelichev" <notifications@github.com

**Comment by Amelichev** [comment]
Ok! Here the new file with other buttons: https://clickpdu.ru/files/hex/cisco.irplus

**Comment by pordog** [comment]
Hi!

It works perfectly.

Thanks!
Peter

2017-10-17 11:47 GMT+02:00 Andrey Amelichev <notifications@github.com>:

**Comment by irplus-remote** [comment]
Thanks, will add the codes to the next version, i guess this can be closed now :)
