### ISSUE TITLE
AOC L22W898

### ISSUE THREAD

**Issue by andersonlaw82** [irplus-remote/irplus-codes.github.io#339]

**Comment by Amelichev** [comment]
Hi! Try this codes: https://clickpdu.ru/files/hex/aoc.irplus
If it works - I can add other buttons.

**Comment by andersonlaw82** [comment]
Awesome, code works great!! Thanks!! Should I close this thread now?

**Comment by andersonlaw82** [comment]
And will the added buttons be a new link or the one above? Thanks again.

**Comment by irplus-remote** [comment]
Hi, thanks again @Amelichev for providing codes and helping out :)
When we have the full file, i will also make a layout and add it to the irplus DB

**Comment by Amelichev** [comment]
Hi! Here the full file: https://clickpdu.ru/files/hex/aoc.irplus

**Comment by irplus-remote** [comment]
Thanks, will close :)
