### ISSUE TITLE
Excelvan YG300 Remote

### ISSUE THREAD

**Issue by JavierGamerFN** [irplus-remote/irplus-codes.github.io#343]
Please add the Excelvan YG300 LED Projector Remote

**Comment by JavierGamerFN** [comment]
OK, so I've finally made the code for this projector myself. 

`<irplus>
<device manufacturer="EXCELVAN" model="YG300" columns="12" format="WINLIRC_NEC1">
<button label="&#1045541;" labelSize="25.0" span="4" backgroundColor="FFFF0000">0xC03F 0xB847</button>
<button label="" labelSize="12.0" span="4" fillColor="FF000000"> </button>
<button label="&#1045889;" labelSize="25.0" span="4">0xC03F 0x40BF</button>
<button label="&#1045599;" labelSize="25.0" span="4">0xC03F 0xE01F</button>
<button label="&#1045518;" labelSize="25.0" span="4">0xC03F 0x9867</button>
<button label="&#1045009;" labelSize="25.0" span="4">0xC03F 0xA05F</button>
<button label="" labelSize="12.0" span="4" fillColor="FF000000"> </button>
<button label="&#1044803;" labelSize="25.0" span="4">0xC03F 0x906F</button>
<button label="" labelSize="12.0" span="4" labelColor="FF000000" backgroundColor="FF000005"> </button>
<button label="&#1044801;" labelSize="25.0" span="4">0xC03F 0x50AF</button>
<button label="OK" labelSize="25.0" span="4">0xC03F 0xD02F</button>
<button label="&#1044802;" labelSize="25.0" span="4">0xC03F 0x10EF</button>
<button label="" labelSize="12.0" span="4" fillColor="FF000000"> </button>
<button label="&#1044800;" labelSize="25.0" span="4">0xC03F 0x807F</button>
<button label="" labelSize="12.0" span="4" fillColor="FF000000"> </button>
<button label="&#1045593;" labelSize="25.0" span="4">0xC03F 0xB04F</button>
<button label="&#1045340;" labelSize="25.0" span="4">0xC03F 0x7887</button>
<button label="&#1044998;" labelSize="25.0" span="4">0xC03F 0xF807</button>
<button label="&#1045364;" labelSize="25.0" span="6">0xC03F 0xA857</button>
<button label="&#1045525;" labelSize="25.0" span="6">0xC03F 0x8877</button>
</device>
</irplus>`

**Comment by JavierGamerFN** [comment]
It's been a long time since this request, but I've received the codes with my PC and the built-in IR receiver of a generic USB Digital TV tuner.
And I also attached a .zip file containing the .irplus file
[EXCELVAN - YG300.zip](https://github.com/irplus-remote/irplus-codes.github.io/files/6870997/EXCELVAN.-.YG300.zip)

**Comment by Sigri44** [comment]
> 

Nice thank you ! Have you code like this for Flipper ?

https://github.com/flipperdevices/flipperzero-firmware/blob/dev/assets/resources/infrared/assets/projector.ir
