### ISSUE TITLE
irplus wave doesn't work on samsung s3 with lineage

### ISSUE THREAD

**Issue by overload** [irplus-remote/irplus-codes.github.io#348]
I tried to install it, bit it doesn't work: the screen work, adds the remotes, but there is no audio when I press a button... so, even if I add IR emitter to audio jack, there is no IR emission.

Could be a problem with lineage os and wave/audio interface? I tried with another smartphone and it work...

**Comment by irplus-remote** [comment]
Hey, do you hear the ir audio with Headphones?

**Comment by irplus-remote** [comment]
Closing, as there was no new answer. If you still have questions please re-open an issue or contact me via mail (app)
