### ISSUE TITLE
led strips usb RGB 

### ISSUE THREAD

**Issue by Goodthink19** [irplus-remote/irplus-codes.github.io#352]
usb led strip made in china

**Comment by irplus-remote** [comment]
There are probably millions of LED strips made in china, it is impossible for me to find codes like that. I can't do more than search on the internet. 

Please see the guide for gathering codes:

https://irplus-remote.github.io/#codes

**Comment by irplus-remote** [comment]
And also try the available ones in the "LED Lights" Section in side the app
