### ISSUE TITLE
Please add smsl devices or how to add devices

### ISSUE THREAD

**Issue by begit** [irplus-remote/irplus-codes.github.io#356]

**Comment by irplus-remote** [comment]
Hi, there is a guide for how to add devices here:

https://irplus-remote.github.io/#codes

If you need a specific device open a new issue with Brand + Model number. 

Add brand "xyz" requests are impossible to fulfill as adding a _single_ codeset takes about 30min-1h. It would be impossible to add a whole brand unfortunately.
