### ISSUE TITLE
irplus LAN python server setup

### ISSUE THREAD

**Issue by MrWoodle** [irplus-remote/irplus-codes.github.io#360]
First, thank you for working on this and sharing. 
Second, I already solved my problem. 
I was using port 8080 for something else. But below is what I was going to post to beg you for help. I would not mind volunteering to update and/or add detail to the instructions if you want a volunteer who is willing to modify them to be a bit more understandable for a noob.  

Thanks. -Wes

I am having issues with the setup of python on raspbian on a RP3.
I verified pigpio and python 2.x 
I figured out that the irplus.py in the instructions was actually named irpluslan.py 
I then I added the IP of my pi inside the ticks (')
Using the same gpio pins so no need to change that line in the file. 
When I issue: "nohup python irpluslan.py &" 
from a terminal window, I get: "nohup: ignoring input and appending output to '/home/pi/nohup.out'"
and nothing works. 
When I just enter: python irpluslan.py 
I get:
Traceback (most recent call last):
  File "irpluslan.py", line 122, in <module> 
   server = HTTPServer(('192.168.166.106', 8080), GetHandler) ...four more file issues and then:
socket.error: [Errno 98] Address already in use

**Comment by irplus-remote** [comment]
Hey, well as you said this sounds like the port 8080 was already i use - so change port.. 
Sure feel free to modify the instruction if something was wrong and let me know what i should change. Or post a pull request (the instructions are on this repo)
https://github.com/irplus-remote/irplus-remote.github.io

**Comment by MrWoodle** [comment]
Could I pay you to 1. Get rid of the ads and 2. have a brief discussion about random issues. I will gladly document everything and share

**Comment by irplus-remote** [comment]
Hi, please contact me via the app About Info Contact

**Comment by irplus-remote** [comment]
I'm closing this as the issue was inactive for quite some time. if you still have any questions please create a new issue and/or write me an email.
