### ISSUE TITLE
LG AKB73775819

### ISSUE THREAD

**Issue by JavierTheBoss** [irplus-remote/irplus-codes.github.io#363]
Hi!
Please add this remote control:
Brand: LG
Model: AKB73775819

**Comment by irplus-remote** [comment]
Hi, did you try the other codes under LG (Bluray) - they should work equally well. What smartphone?

**Comment by JavierTheBoss** [comment]
Smartphone: HUAWEI P9 lite using irplus WAVE

**Comment by JavierTheBoss** [comment]
This remote is for a Home Cinema System

**Comment by irplus-remote** [comment]
Did you try as i said? the AKB codes should work
