### ISSUE TITLE
HK620(RIA 101) does not work 

### ISSUE THREAD

**Issue by Basileu** [irplus-remote/irplus-codes.github.io#365]
Hi there!

First of all, impressive work.

I came across your app while searching for a Android app to control my Harman Kardon HK620 amplifier.
I downloaded and installed the app. Unfortunately it does not work at all with my amplif.
I have tried also PeelRemote, seems to be working alright, despite only having power and volume control.
Your app promises full amplif control, plus the option to control an attached HK tunner so I would like to kindly ask you to provide any hints about the root cause of the problem.
I have tested your app with a SamsungTV, it is working fine, so I don't believe the installation is corrupted.

Thank you and looking forward to your answer!
Basil

**Comment by irplus-remote** [comment]
Can you try? I think this should solve the issue, so i'll close it for now. If you have still problems please answer and i'll re-open

**Comment by Basileu** [comment]
Hi!
I tried the updated config, but still nothing works.
I tried another "remote" from your app, HK AVR, and it seems most of the buttons are working, except tuner input.
