### ISSUE TITLE
NEC leading 0's problem

### ISSUE THREAD

**Issue by CLaw50** [irplus-remote/irplus-codes.github.io#367]
Hi, first of all, thank you for this wonderful app!  :-)

I've a HDTV set top box that uses NEC remote control protocol. The NEC code for each button is something like 0x1B54 0xXXXX, or 0001-1011-0101-0100-xxxx-xxxx-xxxx-xxxx in binary. I found that if I use format="WINLIRC_NEC1" and try to transmit the above NEC code, the three leading 0's did not transmit. So instead of sending 32 pulses, only 29 were sent.

The attach picture shows the problem. The upper waveform is the correct waveform, while the lower waveform is sent by irplus.

![nec-leading-0](https://user-images.githubusercontent.com/37023433/36944463-a8b29376-1fd7-11e8-8821-d229d0030975.gif)

I can work around by using WINLIRC_RAW or WINLIRC_SPACEENC format, but it would be better if this problem is fixed.

**Comment by irplus-remote** [comment]
Hi, i will investigate about this, but it actually looks like to me that this is not really NEC1. Do you have the full RAW sample of this code? Nec1 is always with 32bit but with checksum repeat. e.g 0x1B would follow 0x1BE4 and not 54.  Also which device + model is it? so we can work on adding the device to the irplus list?

**Comment by irplus-remote** [comment]
Also try to enable the setting "Show diagram of infrared codes". And use this code. For me it will correctly output the waveform as in your first diagram. Can you double-check please? 

```xml
<irplus>
    <device manufacturer="NEC1" model="TEST" columns="12" format="WINLIRC_NEC1">

        <button label="TEST" span="3">0x1B54 0xFFFF</button>

    </device>
</irplus>
```

`0000 006C 0022 0002 015B 00AD 0016 0016 0016 0016 0016 0016 0016 0041 0016 0041 0016 0016 0016 0041 0016 0041 0016 0016 0016 0041 0016 0016 0016 0041 0016 0016 0016 0041 0016 0016 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 05F7 015B 0057 0016 0E6C
`
protocol = NEC1-f16, device = 216, subdevice = 42, obc = 255, misc = OBC2=255

**Comment by CLaw50** [comment]
Hi, thanks for your quick answer!

I think I found the reason. I was lazy, instead of writing the 8 digits hex code in 2 groups of 4 digits: 0x1B54 0x8877, I wrote the code in a single group of 8 digits: 0x1B548877. I've tested with some imaginary code, if I wrote the code in 2 groups of 4 digits, irplus always transmits the correct waveform, if I wrote the code in a single group of 8 digits, the leading 0's will not sent.

According to SB-Projects, my set top box uses Extended NEC protocol. The 2nd 8-bits of the code is no longer the invert of the 1st 8-bits, so that more address code can be used, while the 3rd and 4th 8-bits remains the invert of each other.
https://www.sbprojects.net/knowledge/ir/nec.php

The set top box brand name is Magic TV, model no. is 5000D(as far as I know, all MagicTV models use the same remote controller). The code is...

`<irplus>
  <device manufacturer="MagicTV" model="5000D" columns="12" format="WINLIRC_NEC1">
    <space multiple="8" />
    <button label="&#1045541;" labelSize="25.0" span="4" backgroundColor="FFFF4242">0x1B54 0x8877</button>
    <button label="Guide" labelSize="18.0" span="4" labelColor="FF3D3D3D" backgroundColor="FFFFFFFF">0x1B54 0x4CB3</button>
    <button label="Menu" labelSize="18.0" span="4" labelColor="FF3D3D3D" backgroundColor="FFFFFFFF">0x1B54 0xF00F</button>
    <button label="Text" labelSize="18.0" span="4" labelColor="FF3D3D3D" backgroundColor="FFFFFFFF">0x1B54 0xCC33</button>
    <button label="Aspect" labelSize="18.0" span="4" labelColor="FF3D3D3D" backgroundColor="FFFFFFFF">0x1B54 0x2CD3</button>
    <button label="Audio" labelSize="18.0" span="4" labelColor="FF3D3D3D" backgroundColor="FFFFFFFF">0x1B54 0x728D</button>
    <button label="Sub" labelSize="18.0" span="4" labelColor="FF3D3D3D" backgroundColor="FFFFFFFF">0x1B54 0xF20D</button>
    <button label="&#1045569;" labelSize="25.0" span="4">0x1B54 0xAC53</button>
    <button label="&#1046326;" labelSize="25.0" span="4" labelColor="FF00FF00" backgroundColor="FF000000">0x1B54 0x50AF</button>
    <button label="&#1046094;" labelSize="25.0" span="4">0x1B54 0x6C93</button>
    <button label="&#1046320;" labelSize="25.0" span="4" labelColor="FF42FF42" backgroundColor="FF000000">0x1B54 0x30CF</button>
    <button label="OK" labelSize="18.0" span="4" backgroundColor="FF00FF00">0x1B54 0x708F</button>
    <button label="&#1046323;" labelSize="25.0" span="4" labelColor="FF00FF00" backgroundColor="FF000000">0x1B54 0xB04F</button>
    <button label="&#1046364;" labelSize="25.0" span="4" labelColor="FF3D3D3D" backgroundColor="FFFFFFFF">0x1B54 0x28D7</button>
    <button label="&#1046317;" labelSize="25.0" span="4" labelColor="FF00FF00" backgroundColor="FF000000">0x1B54 0xD02F</button>
    <button label="Ch+" labelSize="18.0" span="4" labelColor="FF3D3D3D" backgroundColor="FFFFFFFF">0x1B54 0x6897</button>
    <button label="&#1046365;" labelSize="25.0" span="4" labelColor="FF3D3D3D" backgroundColor="FFFFFFFF">0x1B54 0xA857</button>
    <button label="&#1046366;" labelSize="25.0" span="4" labelColor="FF3D3D3D" backgroundColor="FFFFFFFF">0x1B54 0x18E7</button>
    <button label="Ch-" labelSize="18.0" span="4" labelColor="FF3D3D3D" backgroundColor="FFFFFFFF">0x1B54 0xE817</button>
    <button label="&#1045579;" labelSize="25.0" span="4" backgroundColor="FFFF4242">0x1B54 0x24DB</button>
    <button label="&#1045476;" labelSize="25.0" span="4" labelColor="FF020000" backgroundColor="FFFFFF42">0x1B54 0x44BB</button>
    <button label="&#1045723;" labelSize="25.0" span="4">0x1B54 0xC43B</button>
    <button label="&#1045599;" labelSize="25.0" span="4">0x1B54 0xA45B</button>
    <button label="&#1045514;" labelSize="25.0" span="4" labelColor="FF000000" backgroundColor="FFFFFF42">0x1B54 0x847B</button>
    <button label="&#1045009;" labelSize="25.0" span="4">0x1B54 0x649B</button>
    <button label="&#1045678;" labelSize="25.0" span="4">0x1B54 0xE41B</button>
    <button label="Live" labelSize="18.0" span="4" labelColor="FF3D3D3D" backgroundColor="FFFFFFFF">0x1B54 0xEC13</button>
    <button label="&#1045677;" labelSize="25.0" span="4">0x1B54 0x14EB</button>
    <button label="1" labelSize="18.0" span="4" labelColor="FF3D3D3D" backgroundColor="FFFFFFFF">0x1B54 0x8679</button>
    <button label="2" labelSize="18.0" span="4" labelColor="FF3D3D3D" backgroundColor="FFFFFFFF">0x1B54 0x46B9</button>
    <button label="3" labelSize="18.0" span="4" labelColor="FF3D3D3D" backgroundColor="FFFFFFFF">0x1B54 0xC639</button>
    <button label="4" labelSize="18.0" span="4" labelColor="FF3D3D3D" backgroundColor="FFFFFFFF">0x1B54 0x26D9</button>
    <button label="5" labelSize="18.0" span="4" labelColor="FF3D3D3D" backgroundColor="FFFFFFFF">0x1B54 0xA659</button>
    <button label="6" labelSize="18.0" span="4" labelColor="FF3D3D3D" backgroundColor="FFFFFFFF">0x1B54 0x6699</button>
    <button label="7" labelSize="18.0" span="4" labelColor="FF424242" backgroundColor="FFFFFFFF">0x1B54 0xE619</button>
    <button label="8" labelSize="18.0" span="4" labelColor="FF424242" backgroundColor="FFFFFFFF">0x1B54 0x16E9</button>
    <button label="9" labelSize="18.0" span="4" labelColor="FF424242" backgroundColor="FFFFFFFF">0x1B54 0x9669</button>
    <button label="X" labelSize="18.0" span="4">0x1B54 0x1CE3</button>
    <button label="0" labelSize="18.0" span="4" labelColor="FF424242" backgroundColor="FFFFFFFF">0x1B54 0x06F9</button>
    <button label="&#1044780;" labelSize="25.0" span="4">0x1B54 0x9C63</button>
    <button label="R" labelSize="18.0" span="3" fillColor="FFFF0000">0x1B54 0x12ED</button>
    <button label="G" labelSize="18.0" span="3" fillColor="FF00FF00">0x1B54 0xD22D</button>
    <button label="Y" labelSize="18.0" span="3" fillColor="FFFFFF00">0x1B54 0x32CD</button>
    <button label="B" labelSize="18.0" span="3" fillColor="FF0000FF">0x1B54 0xB24D</button>
  </device>
</irplus>`

**Comment by irplus-remote** [comment]
I guess this can be closed :) If there are any questions or issues feel free to add comments. 

The code for magic tv will be added soon to the new version
