### ISSUE TITLE
WiFi option if no IR

### ISSUE THREAD

**Issue by onebod** [irplus-remote/irplus-codes.github.io#375]
Hi! 
Looks like you have a really good app here.
Would be good if there were an option like on LG TV Plus or AnyMote, where it just connects over the WiFi - no need for a raspberry pi.

**Comment by irplus-remote** [comment]
Hi, Didn't understand this one to be honest. It is not possible to send IR signals via WiFi.

This app is intended to communicate with device's IR protocol. Therefore you need an IR-blaster. Either integrated or external (e.g. Audio port -> irplus WAVE, or a Raspberry/Any other hardware which can send IR).

A WiFi only solution would support only very few devices, like SmartTVs. And those usually have a proprietary protocol which cannot be used without paying fees, or there is a much better app available by the manufacturer itself.

So I'm closing this. If you meant something else feel free to respond :)
