### ISSUE TITLE
Panasonic SA-PT753

### ISSUE THREAD

**Issue by Wafflepanb** [irplus-remote/irplus-codes.github.io#378]
I have been looking everywhere for an app to emulate a Panasonic SA-PT753's remote function. Most apps seem to only be able to get volume and power right. If there is anyway it could be supported in this app I would be so grateful!

**Comment by irplus-remote** [comment]
Hi, any Panasonic pa code working in my app? This would help to identify the master device id then it could be easier to get the other codes

**Comment by John1964Doe** [comment]
Maybe this helps:
[Panasonic SA-PT codes.txt](https://github.com/irplus-remote/irplus-codes.github.io/files/2123426/Panasonic.SA-PT.codes.txt)

**Comment by irplus-remote** [comment]
Converted to irplus remote layout. Can you please try? Rename to *.irplus -> Import
[SA-PT-Series.txt](https://github.com/irplus-remote/irplus-codes.github.io/files/2166838/SA-PT-Series.txt)
