### ISSUE TITLE
Sven HA-430T 

### ISSUE THREAD

**Issue by MAnaH1992** [irplus-remote/irplus-codes.github.io#381]
Please add  Sven HA-430T

**Comment by MAnaH1992** [comment]
[Коды.txt](https://github.com/irplus-remote/irplus-codes.github.io/files/2182126/default.txt)
нехватает 3 команды,помогите пожалуйста,в интернете нигде нету этого пульта, всё что я нашёл,подбирал сам,перебирая команды от других устройств.Заранее спасибо.

**Comment by irplus-remote** [comment]
[HT-475.txt](https://github.com/irplus-remote/irplus-codes.github.io/files/2188939/HT-475.txt)


Could you test please? For import rename to  *.irplus

**Comment by MAnaH1992** [comment]
[Sven.zip](https://github.com/irplus-remote/irplus-codes.github.io/files/2189020/Sven.zip)

**Comment by MAnaH1992** [comment]
Hello, checked: Does not work 5.1 on; 5.1 off, Sw +;
![screenshot_2018-07-15-15-14-55-406_net binarymode android irplus](https://user-images.githubusercontent.com/41086863/42733859-2eada628-8842-11e8-8dcd-9cb809237433.png)
![screenshot_2018-07-15-15-14-50-664_net binarymode android irplus](https://user-images.githubusercontent.com/41086863/42733860-2ed31d86-8842-11e8-9524-6eafb022deaa.png)

**Comment by MAnaH1992** [comment]
These are the commands that I do not have enough 5.1.1on, 5.1off, Tuner ch., Sw +

**Comment by irplus-remote** [comment]
Hi, the file you sent had missing and wrong codes unfortunately.

So if you want to find the missing codes you have to try the full NEC codeset.

See in the app -> Add device -> Example - > NEC1-Full

Test all codes from 0x827D 0x01FE -> 0x827D -> 0xFF00

**Comment by MAnaH1992** [comment]
[SVEN - HA430T.txt](https://github.com/irplus-remote/irplus-codes.github.io/files/2195817/SVEN.-.HA430T.txt)
Rename .irplus this is my file

**Comment by MAnaH1992** [comment]
0x00FF rename 0x827D for each button separately, or can it be done somehow right away?

**Comment by irplus-remote** [comment]
<irplus>
    <device manufacturer="NEC1" model="A156-1-255" columns="12" format="WINLIRC_NEC1">

        <button label="1" span="3">0x827D 0x01FE</button>
        <button label="2" span="3">0x827D 0x02FD</button>
        <button label="3" span="3">0x827D 0x03FC</button>
        <button label="4" span="3">0x827D 0x04FB</button>
        <button label="5" span="3">0x827D 0x05FA</button>
        <button label="6" span="3">0x827D 0x06F9</button>
        <button label="7" span="3">0x827D 0x07F8</button>
        <button label="8" span="3">0x827D 0x08F7</button>
        <button label="9" span="3">0x827D 0x09F6</button>
        <button label="10" span="3">0x827D 0x0AF5</button>
        <button label="11" span="3">0x827D 0x0BF4</button>
        <button label="12" span="3">0x827D 0x0CF3</button>
        <button label="13" span="3">0x827D 0x0DF2</button>
        <button label="14" span="3">0x827D 0x0EF1</button>
        <button label="15" span="3">0x827D 0x0FF0</button>
        <button label="16" span="3">0x827D 0x10EF</button>
        <button label="17" span="3">0x827D 0x11EE</button>
        <button label="18" span="3">0x827D 0x12ED</button>
        <button label="19" span="3">0x827D 0x13EC</button>
        <button label="20" span="3">0x827D 0x14EB</button>
        <button label="21" span="3">0x827D 0x15EA</button>
        <button label="22" span="3">0x827D 0x16E9</button>
        <button label="23" span="3">0x827D 0x17E8</button>
        <button label="24" span="3">0x827D 0x18E7</button>
        <button label="25" span="3">0x827D 0x19E6</button>
        <button label="26" span="3">0x827D 0x1AE5</button>
        <button label="27" span="3">0x827D 0x1BE4</button>
        <button label="28" span="3">0x827D 0x1CE3</button>
        <button label="29" span="3">0x827D 0x1DE2</button>
        <button label="30" span="3">0x827D 0x1EE1</button>
        <button label="31" span="3">0x827D 0x1FE0</button>
        <button label="32" span="3">0x827D 0x20DF</button>
        <button label="33" span="3">0x827D 0x21DE</button>
        <button label="34" span="3">0x827D 0x22DD</button>
        <button label="35" span="3">0x827D 0x23DC</button>
        <button label="36" span="3">0x827D 0x24DB</button>
        <button label="37" span="3">0x827D 0x25DA</button>
        <button label="38" span="3">0x827D 0x26D9</button>
        <button label="39" span="3">0x827D 0x27D8</button>
        <button label="40" span="3">0x827D 0x28D7</button>
        <button label="41" span="3">0x827D 0x29D6</button>
        <button label="42" span="3">0x827D 0x2AD5</button>
        <button label="43" span="3">0x827D 0x2BD4</button>
        <button label="44" span="3">0x827D 0x2CD3</button>
        <button label="45" span="3">0x827D 0x2DD2</button>
        <button label="46" span="3">0x827D 0x2ED1</button>
        <button label="47" span="3">0x827D 0x2FD0</button>
        <button label="48" span="3">0x827D 0x30CF</button>
        <button label="49" span="3">0x827D 0x31CE</button>
        <button label="50" span="3">0x827D 0x32CD</button>
        <button label="51" span="3">0x827D 0x33CC</button>
        <button label="52" span="3">0x827D 0x34CB</button>
        <button label="53" span="3">0x827D 0x35CA</button>
        <button label="54" span="3">0x827D 0x36C9</button>
        <button label="55" span="3">0x827D 0x37C8</button>
        <button label="56" span="3">0x827D 0x38C7</button>
        <button label="57" span="3">0x827D 0x39C6</button>
        <button label="58" span="3">0x827D 0x3AC5</button>
        <button label="59" span="3">0x827D 0x3BC4</button>
        <button label="60" span="3">0x827D 0x3CC3</button>
        <button label="61" span="3">0x827D 0x3DC2</button>
        <button label="62" span="3">0x827D 0x3EC1</button>
        <button label="63" span="3">0x827D 0x3FC0</button>
        <button label="64" span="3">0x827D 0x40BF</button>
        <button label="65" span="3">0x827D 0x41BE</button>
        <button label="66" span="3">0x827D 0x42BD</button>
        <button label="67" span="3">0x827D 0x43BC</button>
        <button label="68" span="3">0x827D 0x44BB</button>
        <button label="69" span="3">0x827D 0x45BA</button>
        <button label="70" span="3">0x827D 0x46B9</button>
        <button label="71" span="3">0x827D 0x47B8</button>
        <button label="72" span="3">0x827D 0x48B7</button>
        <button label="73" span="3">0x827D 0x49B6</button>
        <button label="74" span="3">0x827D 0x4AB5</button>
        <button label="75" span="3">0x827D 0x4BB4</button>
        <button label="76" span="3">0x827D 0x4CB3</button>
        <button label="77" span="3">0x827D 0x4DB2</button>
        <button label="78" span="3">0x827D 0x4EB1</button>
        <button label="79" span="3">0x827D 0x4FB0</button>
        <button label="80" span="3">0x827D 0x50AF</button>
        <button label="81" span="3">0x827D 0x51AE</button>
        <button label="82" span="3">0x827D 0x52AD</button>
        <button label="83" span="3">0x827D 0x53AC</button>
        <button label="84" span="3">0x827D 0x54AB</button>
        <button label="85" span="3">0x827D 0x55AA</button>
        <button label="86" span="3">0x827D 0x56A9</button>
        <button label="87" span="3">0x827D 0x57A8</button>
        <button label="88" span="3">0x827D 0x58A7</button>
        <button label="89" span="3">0x827D 0x59A6</button>
        <button label="90" span="3">0x827D 0x5AA5</button>
        <button label="91" span="3">0x827D 0x5BA4</button>
        <button label="92" span="3">0x827D 0x5CA3</button>
        <button label="93" span="3">0x827D 0x5DA2</button>
        <button label="94" span="3">0x827D 0x5EA1</button>
        <button label="95" span="3">0x827D 0x5FA0</button>
        <button label="96" span="3">0x827D 0x609F</button>
        <button label="97" span="3">0x827D 0x619E</button>
        <button label="98" span="3">0x827D 0x629D</button>
        <button label="99" span="3">0x827D 0x639C</button>
        <button label="100" span="3">0x827D 0x649B</button>
        <button label="101" span="3">0x827D 0x659A</button>
        <button label="102" span="3">0x827D 0x6699</button>
        <button label="103" span="3">0x827D 0x6798</button>
        <button label="104" span="3">0x827D 0x6897</button>
        <button label="105" span="3">0x827D 0x6996</button>
        <button label="106" span="3">0x827D 0x6A95</button>
        <button label="107" span="3">0x827D 0x6B94</button>
        <button label="108" span="3">0x827D 0x6C93</button>
        <button label="109" span="3">0x827D 0x6D92</button>
        <button label="110" span="3">0x827D 0x6E91</button>
        <button label="111" span="3">0x827D 0x6F90</button>
        <button label="112" span="3">0x827D 0x708F</button>
        <button label="113" span="3">0x827D 0x718E</button>
        <button label="114" span="3">0x827D 0x728D</button>
        <button label="115" span="3">0x827D 0x738C</button>
        <button label="116" span="3">0x827D 0x748B</button>
        <button label="117" span="3">0x827D 0x758A</button>
        <button label="118" span="3">0x827D 0x7689</button>
        <button label="119" span="3">0x827D 0x7788</button>
        <button label="120" span="3">0x827D 0x7887</button>
        <button label="121" span="3">0x827D 0x7986</button>
        <button label="122" span="3">0x827D 0x7A85</button>
        <button label="123" span="3">0x827D 0x7B84</button>
        <button label="124" span="3">0x827D 0x7C83</button>
        <button label="125" span="3">0x827D 0x7D82</button>
        <button label="126" span="3">0x827D 0x7E81</button>
        <button label="127" span="3">0x827D 0x7F80</button>
        <button label="128" span="3">0x827D 0x807F</button>
        <button label="129" span="3">0x827D 0x817E</button>
        <button label="130" span="3">0x827D 0x827D</button>
        <button label="131" span="3">0x827D 0x837C</button>
        <button label="132" span="3">0x827D 0x847B</button>
        <button label="133" span="3">0x827D 0x857A</button>
        <button label="134" span="3">0x827D 0x8679</button>
        <button label="135" span="3">0x827D 0x8778</button>
        <button label="136" span="3">0x827D 0x8877</button>
        <button label="137" span="3">0x827D 0x8976</button>
        <button label="138" span="3">0x827D 0x8A75</button>
        <button label="139" span="3">0x827D 0x8B74</button>
        <button label="140" span="3">0x827D 0x8C73</button>
        <button label="141" span="3">0x827D 0x8D72</button>
        <button label="142" span="3">0x827D 0x8E71</button>
        <button label="143" span="3">0x827D 0x8F70</button>
        <button label="144" span="3">0x827D 0x906F</button>
        <button label="145" span="3">0x827D 0x916E</button>
        <button label="146" span="3">0x827D 0x926D</button>
        <button label="147" span="3">0x827D 0x936C</button>
        <button label="148" span="3">0x827D 0x946B</button>
        <button label="149" span="3">0x827D 0x956A</button>
        <button label="150" span="3">0x827D 0x9669</button>
        <button label="151" span="3">0x827D 0x9768</button>
        <button label="152" span="3">0x827D 0x9867</button>
        <button label="153" span="3">0x827D 0x9966</button>
        <button label="154" span="3">0x827D 0x9A65</button>
        <button label="155" span="3">0x827D 0x9B64</button>
        <button label="156" span="3">0x827D 0x9C63</button>
        <button label="157" span="3">0x827D 0x9D62</button>
        <button label="158" span="3">0x827D 0x9E61</button>
        <button label="159" span="3">0x827D 0x9F60</button>
        <button label="160" span="3">0x827D 0xA05F</button>
        <button label="161" span="3">0x827D 0xA15E</button>
        <button label="162" span="3">0x827D 0xA25D</button>
        <button label="163" span="3">0x827D 0xA35C</button>
        <button label="164" span="3">0x827D 0xA45B</button>
        <button label="165" span="3">0x827D 0xA55A</button>
        <button label="166" span="3">0x827D 0xA659</button>
        <button label="167" span="3">0x827D 0xA758</button>
        <button label="168" span="3">0x827D 0xA857</button>
        <button label="169" span="3">0x827D 0xA956</button>
        <button label="170" span="3">0x827D 0xAA55</button>
        <button label="171" span="3">0x827D 0xAB54</button>
        <button label="172" span="3">0x827D 0xAC53</button>
        <button label="173" span="3">0x827D 0xAD52</button>
        <button label="174" span="3">0x827D 0xAE51</button>
        <button label="175" span="3">0x827D 0xAF50</button>
        <button label="176" span="3">0x827D 0xB04F</button>
        <button label="177" span="3">0x827D 0xB14E</button>
        <button label="178" span="3">0x827D 0xB24D</button>
        <button label="179" span="3">0x827D 0xB34C</button>
        <button label="180" span="3">0x827D 0xB44B</button>
        <button label="181" span="3">0x827D 0xB54A</button>
        <button label="182" span="3">0x827D 0xB649</button>
        <button label="183" span="3">0x827D 0xB748</button>
        <button label="184" span="3">0x827D 0xB847</button>
        <button label="185" span="3">0x827D 0xB946</button>
        <button label="186" span="3">0x827D 0xBA45</button>
        <button label="187" span="3">0x827D 0xBB44</button>
        <button label="188" span="3">0x827D 0xBC43</button>
        <button label="189" span="3">0x827D 0xBD42</button>
        <button label="190" span="3">0x827D 0xBE41</button>
        <button label="191" span="3">0x827D 0xBF40</button>
        <button label="192" span="3">0x827D 0xC03F</button>
        <button label="193" span="3">0x827D 0xC13E</button>
        <button label="194" span="3">0x827D 0xC23D</button>
        <button label="195" span="3">0x827D 0xC33C</button>
        <button label="196" span="3">0x827D 0xC43B</button>
        <button label="197" span="3">0x827D 0xC53A</button>
        <button label="198" span="3">0x827D 0xC639</button>
        <button label="199" span="3">0x827D 0xC738</button>
        <button label="200" span="3">0x827D 0xC837</button>
        <button label="201" span="3">0x827D 0xC936</button>
        <button label="202" span="3">0x827D 0xCA35</button>
        <button label="203" span="3">0x827D 0xCB34</button>
        <button label="204" span="3">0x827D 0xCC33</button>
        <button label="205" span="3">0x827D 0xCD32</button>
        <button label="206" span="3">0x827D 0xCE31</button>
        <button label="207" span="3">0x827D 0xCF30</button>
        <button label="208" span="3">0x827D 0xD02F</button>
        <button label="209" span="3">0x827D 0xD12E</button>
        <button label="210" span="3">0x827D 0xD22D</button>
        <button label="211" span="3">0x827D 0xD32C</button>
        <button label="212" span="3">0x827D 0xD42B</button>
        <button label="213" span="3">0x827D 0xD52A</button>
        <button label="214" span="3">0x827D 0xD629</button>
        <button label="215" span="3">0x827D 0xD728</button>
        <button label="216" span="3">0x827D 0xD827</button>
        <button label="217" span="3">0x827D 0xD926</button>
        <button label="218" span="3">0x827D 0xDA25</button>
        <button label="219" span="3">0x827D 0xDB24</button>
        <button label="220" span="3">0x827D 0xDC23</button>
        <button label="221" span="3">0x827D 0xDD22</button>
        <button label="222" span="3">0x827D 0xDE21</button>
        <button label="223" span="3">0x827D 0xDF20</button>
        <button label="224" span="3">0x827D 0xE01F</button>
        <button label="225" span="3">0x827D 0xE11E</button>
        <button label="226" span="3">0x827D 0xE21D</button>
        <button label="227" span="3">0x827D 0xE31C</button>
        <button label="228" span="3">0x827D 0xE41B</button>
        <button label="229" span="3">0x827D 0xE51A</button>
        <button label="230" span="3">0x827D 0xE619</button>
        <button label="231" span="3">0x827D 0xE718</button>
        <button label="232" span="3">0x827D 0xE817</button>
        <button label="233" span="3">0x827D 0xE916</button>
        <button label="234" span="3">0x827D 0xEA15</button>
        <button label="235" span="3">0x827D 0xEB14</button>
        <button label="236" span="3">0x827D 0xEC13</button>
        <button label="237" span="3">0x827D 0xED12</button>
        <button label="238" span="3">0x827D 0xEE11</button>
        <button label="239" span="3">0x827D 0xEF10</button>
        <button label="240" span="3">0x827D 0xF00F</button>
        <button label="241" span="3">0x827D 0xF10E</button>
        <button label="242" span="3">0x827D 0xF20D</button>
        <button label="243" span="3">0x827D 0xF30C</button>
        <button label="244" span="3">0x827D 0xF40B</button>
        <button label="245" span="3">0x827D 0xF50A</button>
        <button label="246" span="3">0x827D 0xF609</button>
        <button label="247" span="3">0x827D 0xF708</button>
        <button label="248" span="3">0x827D 0xF807</button>
        <button label="249" span="3">0x827D 0xF906</button>
        <button label="250" span="3">0x827D 0xFA05</button>
        <button label="251" span="3">0x827D 0xFB04</button>
        <button label="252" span="3">0x827D 0xFC03</button>

        <button label="253" span="3">0x827D 0xFD02</button>
        <button label="254" span="3">0x827D 0xFE01</button>
        <button label="255" span="3">0x827D 0xFF00</button>
        <space multiple="3"/>

    </device>
</irplus>

**Comment by irplus-remote** [comment]
[NEC1-Full.txt](https://github.com/irplus-remote/irplus-codes.github.io/files/2195833/NEC1-Full.txt)

try this file rename to irplus, this has all possible combinations for this device

**Comment by MAnaH1992** [comment]
Thank you

**Comment by MAnaH1992** [comment]
Thank you very much, I scanned all the buttons, everything turned out, I'm very happy, because. I could not find all the buttons for more than two months !! A little later I'll get out the full file of all the commands, maybe someone will need it.

**Comment by MAnaH1992** [comment]
[SVEN - HA430T.txt](https://github.com/irplus-remote/irplus-codes.github.io/files/2196104/SVEN.-.HA430T.txt)
