### ISSUE TITLE
rotel rx-1050 and RSP‐1570

### ISSUE THREAD

**Issue by Frankyzu** [irplus-remote/irplus-codes.github.io#382]
hi admin, please add this ir code to irplus:
thank's in advance
[RSP1570 HEX.pdf](https://github.com/irplus-remote/irplus-codes.github.io/files/2188752/RSP1570.HEX.pdf)

[rot-rec-rx1050 (1).zip](https://github.com/irplus-remote/irplus-codes.github.io/files/2188730/rot-rec-rx1050.1.zip)
[rot-rec-rx1050.zip](https://github.com/irplus-remote/irplus-codes.github.io/files/2188731/rot-rec-rx1050.zip)

**Comment by irplus-remote** [comment]
[RX-1050.txt](https://github.com/irplus-remote/irplus-codes.github.io/files/2188887/RX-1050.txt)

Could you test please? For import rename to  *.irplus

**Comment by Frankyzu** [comment]
perfect, super super perefct, thank you very very much, your the best!!!
