### ISSUE TITLE
Please add Samsung le40a557

### ISSUE THREAD

**Issue by realtebo** [irplus-remote/irplus-codes.github.io#409]
My TV is this

Samsung LE 40A557 P2F

**Comment by irplus-remote** [comment]
Hi, please try those codes. They should work. Especially the BN-Series. I have added Samsung TVs by their remotes as the model numbers are next to infinite.

![image](https://user-images.githubusercontent.com/14196521/50857275-6823bd80-138d-11e9-8825-cd7305d920c5.png)
