### ISSUE TITLE
Pauses in Macros are all playing at once before any other commands.

### ISSUE THREAD

**Issue by path9263** [irplus-remote/irplus-codes.github.io#413]
When creating a macro, whenever I add a pause to the macro in between commands it always plays back the pause first before any of the commands.  Multiple pauses all get played together before any of the other commands as well.  

I am using the irplus **LAN** version 1.9.8 (build 290) on Android 8.1.0

Thank you for the excellent app!

**Comment by irplus-remote** [comment]
Hi can you show the screenshot during macro creation to see how you did it? I tried and i think it works fine. Any specific  device?

**Comment by path9263** [comment]
Sure, [here is a very simple one](https://i.imgur.com/ZSymsWV.png), it just switches between two input sources with a 4sec pause in between.  I can watch the stereo when it is issued, it just pauses for 4 seconds then very quickly switches between the two.  

Devices is a Nexus 6P. 

Thank you for your help!

**Comment by irplus-remote** [comment]
Uh i guess it must be something related to the LAN version only. 
Which connection are you using? HTTP or Bluetooth?

**Comment by path9263** [comment]
I am using HTTP.  I should maybe mention that I am using my own client to receive the commands but I can watch and see that the client does not receive anything until 4 seconds after I push the button.  

Again, thank you.

**Comment by irplus-remote** [comment]
Hi, i have fixed the issue (hopefully) with the last version.

Try this apk:
https://drive.google.com/open?id=1MlMdZwV01UTfyrnt-G_Am2tsdLr0eh4D
Will be pushed to store soon ;)

**Comment by path9263** [comment]
Thank you for that! Unfortunately I'm away from home for a week but I'll let you know how it works when I get back.

**Comment by path9263** [comment]
That fixed it!  Thank you so much!
