### ISSUE TITLE
Request for Samsung AA59-00508A 

### ISSUE THREAD

**Issue by ungeskriptet** [irplus-remote/irplus-codes.github.io#417]

**Comment by irplus-remote** [comment]
Could you try the other AA59 remotes? They should work. Sometimes the key-labels are not exactly the same but they should work..
If you can tell me the necessary rename i can add a separate entry for it.

See inside the app:
  - >SAMSUNG (TV) (AA)

If you have a working remote and need a rename you can do this inside the editor of the app. and post it here so i know what needs to be changed.

EXAMPLE: "SMART-HUB" @ AA59-00786A  ->> "DOLBY" @ AA59-00508A
