### ISSUE TITLE
Missing implementation of the LIRC "repeat_mask" command

### ISSUE THREAD

**Issue by vatonek** [irplus-remote/irplus-codes.github.io#423]
Description:
The lircd.conf man page says:
 - **_repeat_mask \<mask\>_**  Mask defines which bits are inverted for repeats. 

If one imports the lirc.conf file containing this command, IRplus does not accept the repeat_mask command and emits wrong IR signal.

Example:
If lircd.conf file contains:

 gap-pulse="260" 
 gap-space="43550"
 repeat="2"
 repeat-mask="0x03FF" 
and
 \<button label="POWER"\> 0x41A2  \</button\>

in the \<device\> section, then if the POWER button is pressed, the

 - LIRC emits two different data sequences, separated by the gap-space:
  \<data 0x41A2\> \<gap\> \<data 0x425D\>
where 0x425D = 0x41A2 .xor. 0x03FF.

 - IRplus seems to ignore the repeat_mask command so it repeats the first data sequence unchanged:
  \<data 0x41A2\> \<gap\> \<data 0x41A2\>

**Comment by irplus-remote** [comment]
It is true that repeat_mask is not supported. However it is still possible to support toggle bits. 
Can you please post the full lirc file of the remote so i can properly test it?

You can however use irscrutinizer to import that lirc file and export it with an _unset_ T (Toggle bit) and export it to irplus format. Then the toggle-bit will be considered by exporting alternating pronto-codes for 0 and 1

**Comment by vatonek** [comment]
and this is the Pronto equivalent:
[TestSharpPronto.txt](https://github.com/irplus-remote/irplus-codes.github.io/files/2775561/TestSharpPronto.txt)

**Comment by vatonek** [comment]
Data stream of each key cosists of two 15-bit fields, each followed by the "gap". There is no header, no leading pulse, no trailer. Bits 14, 13, 12, 11, and 10 repeat in both fields unchanged, while bits 09, 08, 07, 06, 05, 04, 03, 02, 01, 00 in the second sequence are inverted (Sharp TV remote).

**Comment by irplus-remote** [comment]
Ah ok i understand. yea it is not really a bug but rather a "feature did not exist" ;-) I will try to consider it for the next version. Maybe it could help to replace some pronto-codes with lirc codes and make the database smaller. But i don't know if its really needed as sharp isnt used THAT often - it could be fine to just use PRONTO for those. But ill keep the issue open

**Comment by vatonek** [comment]
Thanks. I know it is a rare case. But as far as I can guess it would nt be too complicated to add this "nonexisting feature" :-). May by I will help with it by testing, even by programmming? I am experienced programmer, just from the old ages of computing (1970 - 1990) :))

**Comment by vatonek** [comment]
I have also in mind some better solution, but this need syntax change, so it is much difficult to implement. Something like this:
      \<burst name="mygap" pulse="260" space="43550"\>\</burst\>
      \<button label="POWER"\>  0x41A2  mygap  0x425D  \</button\>

First line defines an unique burst (pulse/space sequence) named "myburst", while the next one is redefined "button", allowing more complex argument, in this case two different hex data sequences, separated by previously defined burst.

**Comment by vatonek** [comment]
which language?

**Comment by irplus-remote** [comment]
Your second solution is more difficult to implement also it would make importing harder so i'd rather prefer a way to calculate the second part  :-) 
In Java (Posted the link)

**Comment by vatonek** [comment]
In C you can find example in https://www.dummies.com/programming/c/how-to-use-the-bitwise-exclusive-or-xor-operator-in-c-programming/

**Comment by vatonek** [comment]
In Java https://www.tutorialspoint.com/java/java_bitwise_operators_examples.htm

**Comment by irplus-remote** [comment]
Ok i have implemented the first variant
This codefile now should work correctly:

```xml
<irplus>
    <device manufacturer="TEST_LIRC" model="2" format="WINLIRC_SPACEENC" bits="15" one-pulse="260" one-space="1840"
        zero-pulse="260" zero-space="790" gap-pulse="260" gap-space="43550" repeat="2" repeatmask="0x03FF">
        <button label="POWER">0x41A2</button>
        <button label="UP">0x43AA</button>
        <button label="DOWN">0x4012</button>
        <button label="OK">0x412A</button>
    </device>
</irplus>

```
![image](https://user-images.githubusercontent.com/14196521/51428964-f3147b80-1c09-11e9-9f55-bb312e0328cf.png)


Beta-APK build 298
https://drive.google.com/file/d/1C7Txmakbgp1c9W5VgvlbrWMeQh8hWS4R/view?usp=sharing

If you have the real device to test it . feel free ;-)

**Comment by vatonek** [comment]
Yes, more difficult, but much more powerfull, allowing almost any remote code describe in compressed format. This way you can replace allmost all those exotic bursts predefined in the LIRC.

For this special case even there is no need for the user burst definition, as standard LIRC gap can be used.

**Comment by vatonek** [comment]
Yes, I have. I will try. Thanks for such unbeliveably fast response :))

**Comment by vatonek** [comment]
GREAT, WORKING !!!

**Comment by vatonek** [comment]
Seems everything is working. Have not tested every button, but all I tested worked. Here is the complete configuration file (correct name SHARP - GA857WJSA.irplus):

[SHARP - GA857WJSA-lirc.irplus.txt](https://github.com/irplus-remote/irplus-codes.github.io/files/2776075/SHARP.-.GA857WJSA-lirc.irplus.txt)

**Comment by irplus-remote** [comment]
Do you  have the lirc file too ? Recorded from real remote or found on the net? Just to compare it with. I have some automated tools which avoid copy+paste errors etc.
