### ISSUE TITLE
Empty button crashed after update

### ISSUE THREAD

**Issue by HelenFoster** [irplus-remote/irplus-codes.github.io#442]
On some previous version I imported an XML file which included an empty button `<button span="4"></button>` and it appeared as a blank button with a width of 4. After an irplus update (currently on 1.9.9 but I'm not sure when this happened), the app started to crash immediately upon opening. Clearing the app data stopped it crashing, but after I imported the same XML file again, it started crashing again. In the end, deleting the empty button from the XML resolved it. (Observed on a stock Galaxy S4.)

**Comment by irplus-remote** [comment]
Hi, please use this tag for empty buttons

```xml
    <space multiple="4"/>
```

The bug itself is fixed for the next version. You could also avoid it by placing a space bettween the tag
