### ISSUE TITLE
portrair (reverse) problem

### ISSUE THREAD

**Issue by sam73dz** [irplus-remote/irplus-codes.github.io#448]
Hello,

The fonction portrait (reverse) is not operational.

regards.

Samir

**Comment by Mathew61** [comment]
Sandramee84@gmail.com

**Comment by Mathew61** [comment]
Sandramee84@gmail.com

**Comment by irplus-remote** [comment]
Hey, note that it does only work if rotation is not locked in the system settings. After you have set rotation-allowed it should work. If you still have problems after enabling it , please show a screenshot with what happens and with the settings. Thanks
