### ISSUE TITLE
IR code format documentation?

### ISSUE THREAD

**Issue by CaspianRoach** [irplus-remote/irplus-codes.github.io#458]
I would like to edit some codes I found for my device (more specifically, add a number of 'repeats' onto a specific button) as my phone's default IR signal repeat is dreadfully slow when doing it 1-by-1, and would like to know the specifics or the examples of how to correct the codes so some buttons include built-in repeats.

For example, I have a WINLIRC_NEC1 code of

    0x00ff 0x926d

I see the formatting in the table as

   frequency, repeat, repeatheader, bits, pre-bits

but it's not specific in how many bits each part is taking. Is there a more specific format documentation for this? How many bits the 'frequency' part takes and how many bits does the 'repeat' part takes? Is 'repeatheader' a binary setting? I tried searching the WINLIRC documentation but didn't find something like this, so I assume it's a code storage format you made yourself?

If you could point me in the direction that I can research it further that would be much appreciated.

**Comment by HeartbliT** [comment]
![IMG_20171010_053108](https://user-images.githubusercontent.com/35906077/70317627-6a50ff00-181e-11ea-82cf-c2cd1677e577.jpg)

**Comment by irplus-remote** [comment]
Hi, the frequency is just the pulse-width modulation, which in 99% is 38000Hz ~ 38KHz
The NEC1 protocol is specified like this: https://www.sbprojects.net/projects/ircontrol/nec.php

A drawing how to convert the bits to winlirc_nec1
![image](https://user-images.githubusercontent.com/14196521/70318801-29a6b500-1821-11ea-8daf-fac65b188c86.png)


If you want a more "exact" format you can use "WINLIRC_RAW"

**Comment by CaspianRoach** [comment]
Oh, I see. After reading the article in your link, it seems that it's not that simple to add repeats on a single command, since it says a 'repeat' message is a separate message and I thought I could encode them into the same one. 

I'm not bothered enough to learn the RAW format, I'll just settle with slow manual repeats, it's not a big deal. Thanks for answering and providing clarity!
