### ISSUE TITLE
Add IR code

### ISSUE THREAD

**Issue by R34GTR** [irplus-remote/irplus-codes.github.io#460]
Please add IR code from samsung AK59-00061H remote controller.

Also add code for Maxxo T2 H.265 Senior, DVB-T2  settopbox.

**Comment by white-devil42** [comment]
Plz add Cisco IS13252

**Comment by irplus-remote** [comment]
cleaning up, each issue has to be in own request, and the device must be found by google , IS13252 seems to be wrong as it cannot be found.
Created issue for Maxxo #474
