### ISSUE TITLE
Naim amplifiers ir codeset

### ISSUE THREAD

**Issue by dsacristan** [irplus-remote/irplus-codes.github.io#473]
I've been looking for an app like irplus to control my Naim nait xs3 amplifier and other devices (thank you very much for it!!). So, I want to share a irplus layout with the RC5 codeset provided by Naim for its family of ampliers and preamplifiers. Naim uses the RC5 protocol in its products, so it should be easy to extend the profile to other products like CD's or tunners.

Attached you will find the folowing files:

- **Naim amplifiers RC5 codes.xlsx** provided by the Naim support team
- **NaimRC5codes.irplus**, with a direct translation of the codeset provided
- **NAIM - nait.irplus**, with a selection of commands that works with my Naim nait xs3. This layout it's supposed to be working with all the Naim's amplifiers and others that work with the RC5 protocol
- **csv2irplus.ps1** The powershell script used to process the code list into a irplus file

I didn't succeed in getting the discrete commands to work. In particular, the fast volume codes did't work for me. Due that I set the repeat frequency to 50ms to get the regular volume works in a proper way

References: https://en.wikipedia.org/wiki/RC-5
[NAIM RC5 ir codes - irplus.zip](https://github.com/irplus-remote/irplus-codes.github.io/files/4165780/NAIM.RC5.ir.codes.-.irplus.zip)

**Comment by irplus-remote** [comment]
Hi, thanks for providing the files, i have added them to the app (available with next update or online update via add files)

About the volume: I will try to add a way to set the repeat frequency for each button separately when needed to circumvent the issue. Thanks again for the feedback!
