### ISSUE TITLE
Please add New Device - Fan Hoffen ( produced by mPTech ) model: TST08-RD

### ISSUE THREAD

**Issue by toonek** [irplus-remote/irplus-codes.github.io#491]
Hello,

Could you add a new remote for the Fan:
Hoffen TST08-RD produced by mPTech - it is own brand of Polish stores Biedronka ( Jeronimo Martins)
https://hoffen.com.pl/produkty/wentylator-kolumnowy-z-pilotem/

I had lost my remote but found an app for android called "IR code finder" - it is NEC protocol finder/scanner.
So I am able to use my xiaomi phone with it but only two buttons can be stored so it would be nice to have it in irplus app.

Codes are in dec:
on/off -  dev 0 command 24   ,full hex: 00ff18e7
mode -  dev 0 command 144  ,full hex: 00ff906f
swing -  dev 0 command 162 , full hex: 00ffa25d
timer -  dev 0 command 224  ,full hex: 00ffe01f
speed -  dev 0 command 226  ,full hex: 00ffe21d

**Comment by toonek** [comment]
After some reading I was abble to make some xml for import.
I had use IrScrutinizer and ir code converter http://irdb.tk/encode/ but only power button works. I use NEC1 as a code source for pronto code> Any idea what is wrong ?

<irplus>
    
    <device manufacturer="Hoffen" model="TST08-RD" format="PRONTO_HEX" columns="12">

        
        <button label="POWER"  span="4">0000 006C 0022 0002 015B 00AD 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0016 0016 0016 0016 0016 0016 0041 0016 0041 0016 0016 0016 0016 0016 0016 0016 0041 0016 0041 0016 0041 0016 0016 0016 0016 0016 0041 0016 0041 0016 0041 0016 05F7 015B 0057 0016 0E6C</button>  
        <button label="MODE"   span="4">0000 006C 0022 0002 015B 00AD 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0016 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0016 0016 0041 0016 0041 0016 0016 0016 05F7 015B 0057 0016 0E6C</button>
	 	<button label="SWING"  span="4">0000 006C 0022 0002 015B 00AD 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0016 0016 0041 0016 0016 0016 0016 0016 0016 0016 0041 0016 0016 0016 0041 0016 0041 0016 0016 0016 0041 0016 0041 0016 0041 0016 0016 0016 0041 0016 0016 0016 05F7 015B 0057 0016 0E6C</button>
		<button label="TIMER"  span="4">0000 006C 0022 0002 015B 00AD 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0016 0016 0016 0016 0016 0016 05F7 015B 0057 0016 0E6C</button>
		<button label="SPEED"  span="4">0000 006C 0022 0002 015B 00AD 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0016 0016 0041 0016 0016 0016 0016 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0016 0016 0041 0016 0041 0016 0041 0016 0016 0016 0016 0016 0016 0016 05F7 015B 0057 0016 0E6C</button>
		
		
    </device>
</irplus>

**Comment by toonek** [comment]
Ok, some more tries and I found work around.
I really do not understand why, but it works.
So I used IrScrutinizer generator ->Protocol NEC1 -> D is dec fo device, S is dec for sub device ( 255- device) F is command code in dec (use hex calculator if needed). Found some explanation about NEC hex protocol
NEC protocol:
   <--   Byte 1   --> <--            Byte 2           --> <-- Byte 3 --> <--         Byte 4         -->
   Manufacturer code | binary reversed manufacturer code | command code | bynary reversed command code | 

For my  power button it looks like that:
 dev 0 command 24 ,full hex: 00ff18e7 (00=0 FF=255 18=24 e7=231  231+24=255 )
D 0 S 255 F 24
IrScrutinizer generator ->Protocol NEC1 -> export to LIRC -> open last export file, copy all -> convert lirc to irplus on this website https://irplus-remote.github.io/converter/lirc.html -> and save as .xml or txt in any text editor:
<irplus>
	<device manufacturer="MANUFACTURER" model="MODEL" columns="12" format="WINLIRC_SPACEENC" bits="32" pre-bits="32" toggle-bit-pos="" gap-pulse="564" gap-space="108000" one-pulse="564" one-space="1692" zero-pulse="564" zero-space="564" header-pulse="9024" header-space="4512">
		<button label="NEC1_D0S255F24" span="4">0x0000000000FF18E7</button>
	</device>
</irplus>

This work for power button. As we see the code  it is almost the same as full hex from"Ir code finder"
button label="NEC1_D0S255F24" span="4">0x0000000000_FF18E7_</button>      00_ff18e7_

I had tried for the rest buttons and it didn`t work... but the IrScrutinizer export looks a little different.
For code 144 - 00ff_906f_ it generated NEC1_D0S255F144	0x0000000000_FF09F6_ . As you see last two bytes were reversed.
When i reversed it back it works and I have remote for my Fan.
the xml file for the import in irplus looks now like that and works:

 <irplus>
	<device manufacturer="Hoffen" model="TST08-RD" columns="12" format="WINLIRC_SPACEENC" bits="32" pre-bits="32" toggle-bit-pos="" gap-pulse="564" gap-space="108000" one-pulse="564" one-space="1692" zero-pulse="564" zero-space="564" header-pulse="9024" header-space="4512">
		<button label="Power" span="4">0x0000000000FF18E7</button>
		<button label="Mode" span="4">0x0000000000FF906f</button>
		<button label="Swing" span="4">0x0000000000FFa25d</button>
		<button label="Timer" span="4">0x0000000000FFe01f</button>
		<button label="Speed" span="4">0x0000000000FFe21d</button>
	</device>
</irplus>

[hoffen_TST08-RD.txt](https://github.com/irplus-remote/irplus-codes.github.io/files/4892684/hoffen_TST08-RD.txt)

**Comment by irplus-remote** [comment]
Thank you very much for your input! Note that NEC1 LIRC notation is not exactly like the regular NEC notation. 
Ive made a drawing here which shoudl explain why: https://github.com/irplus-remote/irplus-codes.github.io/issues/458
