### ISSUE TITLE
Missing remote for Genius SW-HF 5.1 5005

### ISSUE THREAD

**Issue by victortrifonov** [irplus-remote/irplus-codes.github.io#499]
Hi,
I have audio system Genius SW-HF 5.1 5005 and I am able to control it through irplus with  SW-HF 5.1 5000, but I miss the following controls:

- Center +/-

- Woofer +/-

- Surround +/-

Would it be possible to create a dedicated remote for SW-HF 5.1 5005?
My original remote is long gone and the system is very old, so irplus is my only option.
Thanks in advance!

**Comment by CustardFlan** [comment]
Hey! i wanna help you, simply download the attached file
[TEST Genius SW-HF 5.1 5005.zip](https://github.com/irplus-remote/irplus-codes.github.io/files/5374997/TEST.Genius.SW-HF.5.1.5005.zip)

 import that to the app, test the buttos named: D:192-S:63-FXXX and tell me if works for you, when you done testing, simply edit the remote and delete the ones that does't work, rename and, thats it!

``

**Comment by victortrifonov** [comment]
Hi,
Thank you very much for the codes!
Unfortunately none of them is working. This being said, I checked online
and found out that the original remote does not have such buttons i.e. most
probably controlling these functions is not possible with the remote.


Regards,
Victor Trifonov
Mob +359 888 098 883
victor.trifonov@gmail.com

**Comment by irplus-remote** [comment]
Hi, I've added the Codefile for the 5200 series in the online list (UPDATE LIST) on Add Device. Maybe it works with the 5005 too.

Original Issue: https://github.com/irplus-remote/irplus-codes.github.io/issues/504
