### ISSUE TITLE
Genius SW-HF5.1 5200 audio device (working config)

### ISSUE THREAD

**Issue by giolaza** [irplus-remote/irplus-codes.github.io#504]
Hello, Thank you for soft.
Here is working config for Genius Speakers

[Genius.SW-HF5.1.5200.irplus.txt](https://github.com/irplus-remote/irplus-codes.github.io/files/5553106/Genius.SW-HF5.1.5200.irplus.txt)

**Comment by irplus-remote** [comment]
Hi, Thank you very much for providing those 👍 , and sorry for the late answer. I've added it for latest version!  (Update online list)
