### ISSUE TITLE
Bn59 01224b

### ISSUE THREAD

**Issue by hojjat26** [irplus-remote/irplus-codes.github.io#510]
درخواست
#

**Comment by irplus-remote** [comment]
Sorry, but i can't speak arabic. Also the available samsung remotes should work with BN59. Please test them. Also write down the used smartphone and android versions for future requests. Thanks

**Comment by hojjat26** [comment]
در تاریخ سه‌شنبه ۲۳ دی ۱۳۹۹ ه‍.ش.،‏ ۱۲:۱۲ irplus-remote <
notifications@github.com> نوشت:
