### ISSUE TITLE
Genius SW-5.1 HT - 4 button remote controller

### ISSUE THREAD

**Issue by nunobett** [irplus-remote/irplus-codes.github.io#511]
Hi,

Any chance someone could find the IR codes for this old device Genius SW-5.1 HT (Home Theater)? 

It is a 4 button remote controller for Volume Up and Down, Power and Mute.

I've tried other genius 5.1 codes, but those do not seem to work.

Thanks in advance,
NB

![3b4e5e61bbc6096ac94f2e35027bf871 image 330x309~2](https://user-images.githubusercontent.com/596858/103161754-08bb5400-47d6-11eb-9572-dd3282a743c2.jpg)

**Comment by irplus-remote** [comment]
Hi, what smartphone are you using? You confirm that irplus is working for other remotes? Also, can you please make sure you pointed directly at the IR-receiver while testing the other Genius codes?

**Comment by irplus-remote** [comment]
Actually the remote seems to be the same used for MBO ASL 1000

**Comment by nunobett** [comment]
Hi, I'm using a Xiaomi Mi A3. I'll try the MBO ASL 1000 config.

**Comment by mirdza83** [comment]
Hi, I am also having trouble controling my Genius SW-5.1 HT. The buttons dosent seem to work. Remote for my LG TV works fine.

**Comment by LehanF** [comment]
the same story.

**Comment by irplus-remote** [comment]
Yes i know, the codes are not available. I dont find them in the internet as well. So the only option is someone with the real remote is to help me to gather them, using a raspberry or lirc reader

**Comment by LehanF** [comment]
maybe there is an opportunity to somehow pick up by wholesale?  is there such a program?  maybe I would sit at my leisure to pick up.

**Comment by LehanF** [comment]
maybe there is an opportunity, how to pick it up, by bulk?  is there such a program?  maybe I could find time to pick.

**Comment by irplus-remote** [comment]
If you have the real remote you can gather the codes by using a PC or Raspberry with IR-receiver attached to it. See the guides:
https://irplus-remote.github.io/#learning

**Comment by LehanF** [comment]
if I had it.  I think that I would hardly be interested in this topic.  he has long been lost somewhere.

**Comment by mirdza83** [comment]
My friend has the same HT system and remote. I will try to build an IR receiver and if I am successful I will post the codes here. Cheers

**Comment by LehanF** [comment]
it would be great!  I hope we are talking about the same thing.
![pult-ot-akusticheskoy-sistemy-genius-sw-5-1-home-theater-1-10857777](https://user-images.githubusercontent.com/77320360/104413559-94c3ce80-557f-11eb-89f8-508db1bac695.jpg)

**Comment by mirdza83** [comment]
yeah, that's the one

**Comment by LehanF** [comment]
then we look forward to your codes

**Comment by mirdza83** [comment]
Here you go...
[Genius SW-5.1 HT.irplus.zip](https://github.com/irplus-remote/irplus-codes.github.io/files/5815966/Genius.SW-5.1.HT.irplus.zip)

Unzip the file then import in the app (MENU/IMPORT/FILE)

P.S It would be nice if the author updates the list so everyone can have the codes. ;)

**Comment by LehanF** [comment]
Hurrah!!!  works!  at last!  thank you very much!!! 😁😁😁👍🏻👍🏻👍🏻

**Comment by irplus-remote** [comment]
Perfect! Well done 👍  I've updated the code for build 306 and 307. (Just press on UPDATE LIST) then the GENIUS / SW 5.1 HT is updated. I found out the reason why the currently available code did not work. There was a bit missing in the encoding at the end. But the raw one is now working and I think we can tread this as case-closed :D

**Comment by CryptorClub** [comment]
> Perfect! Well done +1 I've updated the code for build 306 and 307. (Just press on UPDATE LIST) then the GENIUS / SW 5.1 HT is updated. I found out the reason why the currently available code did not work. There was a bit missing in the encoding at the end. But the raw one is now working and I think we can treat this as case-closed :D

Thank you, its worked! Anyway needed to click each button twice to get effect. Maybe some another bit was missed...

**Comment by Jiwes** [comment]
> Here you go... [Genius SW-5.1 HT.irplus.zip](https://github.com/irplus-remote/irplus-codes.github.io/files/5815966/Genius.SW-5.1.HT.irplus.zip)
> 
> Unzip the file then import in the app (MENU/IMPORT/FILE)
> 
> It would be nice if the author updates the list so everyone can have the codes. ;)

**Comment by Jiwes** [comment]
Is possible to convert irplus file to .Ir file (flipper zero format) ?
