### ISSUE TITLE
Problem with Telesystem TS 7.1 7.2 7.3 7.4 DT

### ISSUE THREAD

**Issue by zyzz777** [irplus-remote/irplus-codes.github.io#517]
Hi, I don't know if it's my problem, or maybe the code/frequency problem, but when I use Telesystem 7.1 remote, only few buttons work properly, like Ch+ Ch- Vol+ Vol- and the 4 direction buttons, the other buttons work too, but only if I send another signal from the remote, like I have to press a random button on my remote and then press the button on the app to make the button work.

Example: I press the power button on the app, doesn't work, so I press a random button (like ch 5) on my remote, now I press power button on the app and works.

What's the cause of this? My remote works properly

I don't understand much of frequencies and headers gaps etc, I repeat that every button is mapped right, but for some reason doesn't reach the signal

**Comment by irplus-remote** [comment]
Hi, is it the TS 7.1 DT you are referring to?

**Comment by zyzz777** [comment]
Yes

**Comment by irplus-remote** [comment]
This device does not use NEC protocol. The issue here should be the missing toggle bit. 
Could you please try to use the "STRONG / SRT5011 DVB-T" code? This should be compatible and better working. If you can confirm, i will replace the TS 7.1 code with it.

**Comment by zyzz777** [comment]
Yes this works properly thanks

**Comment by irplus-remote** [comment]
No, the reason is that the codefile was using only the same toggle-bit , instead the strong one, correctly switches the toggle-bit for each press. So it was a good find! 👍

**Comment by irplus-remote** [comment]
By the way do the buttons correspond to the correct functions written on them? If not could you correct please?

**Comment by zyzz777** [comment]
Yes, only the AV button isn't doing nothing, maybe because I have only one monitor attached, but everything works fine
