### ISSUE TITLE
XIAOMI Redmi Note 9s not available on google play for install

### ISSUE THREAD

**Issue by euquiq** [irplus-remote/irplus-codes.github.io#531]
Hello! 

As the title says: My phone includes an IR Blaster, but your compiled app is not available for it on Play Store. I read the earlier issue about some new phones using a propietary api for their IR, is this the case too ? I hope it is only a matter of adding this model into the available ones inside the play store.

Thanks!

**Comment by irplus-remote** [comment]
Hi, i think the 9s is not in the playstore library thats the reason it doesnt show up. Do you know if it is called in a different way? Did you modify the ROM in any way? 


![image](https://user-images.githubusercontent.com/14196521/111333438-fcc38d80-8672-11eb-9036-4513c7b06c11.png)

**Comment by euquiq** [comment]
Hello! Yes, it is the "curtana" one.

Yet, for some unknown reason, When I try to install your app on my phone, it is not enabled.

I do not have this problem with any other app I know of. It would be interesting to know why the play store is denying your app to this particular phone.

Maybe you can expand the curtana row (right where you captured that screen), where you have access to the device details, and hopefully there is some further clues / information about it ? 

I do have several (dozens) of published apps myself, on Google's Play Store, and I can install my own apps on my phone with no problem. I did reach to the Device catalog from one of those apps, and expanded the CURTANA row: There is a button you can press in order to EXCLUDE that phone from install. Maybe at some point you did set up the exclude as default value or something along those lines ?

Hopefully you can give it a look. Regards, and thanks for your earlier answer,

Enrique.

**Comment by irplus-remote** [comment]
Nope they are all included. Could you please show a screenshot of the "device" tab in cpu-z maybe you have a variant of the phone? Also from which country are you? I noticed that some countries were excluded and now i have added them.

Out of curiosity: Do you see irplusLAN and WAVE while searching for irplus in the store?

**Comment by euquiq** [comment]
I live in Uruguay. I can see and install both irplusLAN and WAVE. I have a standard xiaomi redmi note 9s, nothing special about it, just a nice cheap chinese phone.

![6623727c-4fbe-4ebe-8d0d-4ffdd8d23a9d](https://user-images.githubusercontent.com/31453004/111476522-000b5780-870d-11eb-887a-a29a99c15e30.jpg)

**Comment by irplus-remote** [comment]
Hm is this a non-stock rom? Why does it say aosp_curtana?

**Comment by euquiq** [comment]
Yes it is not the Xiaomi rom (awful chinese thingy:  I am using a vanilla Android 10, the one from pixel Experience (https://download.pixelexperience.org). I have the original xiaomi's IR app installed (working ok), but it is somewhat buggy and limited.

**Comment by irplus-remote** [comment]
Could it be that the ROM is wrongly being detected as Pixel phone? I have disabled all Pixel phones from the Store because obviously they don't have IR. Can you ask anyone else or on XDA if they can install irplus with the same ROM. I think then it is something they have to change. I use myself (and have available) many Redmi/Xiaomi phones for testing as they are the last bastion of IR blasters. With the STOCK rom it always worked :/

**Comment by euquiq** [comment]
Maybe then it is due to that: if you disabled pixel phones, it would explain why I can still see your other two apps, but not specifically this one. 

Hopefully there Is a way you can provide me with an url for downloading the compiled apk outside the play store ? (I can pay for it, if possible, through paypal) ? I am on gmail with this same nick.

**Comment by irplus-remote** [comment]
No problem just drop me an email to binarymode.android@gmail.com i will answer with the APK on drive. Though it is a trunk build as i cannot currently build the one in the playstore. So you can actually will beta test ;) And no need to pay obviously ;)

**Comment by euquiq** [comment]
Thanks! email sent
