### ISSUE TITLE
Macro using button with icon instead label

### ISSUE THREAD

**Issue by Pokec** [irplus-remote/irplus-codes.github.io#574]
Hi. A great feature of irplus is the ability to create macros. However, sometimes I need to use a button containing an icon instead of a label for a macro. Such a macro can be created, but information about the icon code is lost from macro during further editing or use. It seems that button with icon cannot be successfully used in the macro. Please, can this be enabled? Alternatively, can a non-displayed label be inserted into the button along with the icon for use in a macro?

**Comment by irplus-remote** [comment]
Could you please make some screenshot(s) or small video to visualize the issue? I did not quite understand. Just tried using an icon - and it worked for me. Thanks

**Comment by Pokec** [comment]
Excuse me, you're right. I was hasty, because the macro didn't work for another reason due to my own mistake. 
Once again, I apologize. Very very sorry.
