### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by chrisantmumo** [irplus-remote/irplus-codes.github.io#582]
Hi I made an IR blaster it's working on my Sony bravia but has refused to work on my Sony home theater kindly assist

**Comment by irplus-remote** [comment]
Hey, please specify the exact model number of the device you're trying to control. Also an image of the real remote could be helpful!

**Comment by chrisantmumo** [comment]
The model number is  Sony DZ520K attached is the remote control

**Comment by irplus-remote** [comment]
Ive made a quick research and could not find any codes on the internet. Did you try various available SONY AVR Codes (try some or all) if you find any code which does do something on your device (Note: even if buttons don't match, it could be a hint) to find the correct codeset..

**Comment by irplus-remote** [comment]
If you have the genuine remote you could create a lirc file on your own using a raspberrypi or one of the other methods specified on the website though..

https://irplus-remote.github.io/#learning -> Ways to read codes from the real device remote:

**Comment by chrisantmumo** [comment]
Last week it was working then all over a sudden it stopped yesterday but the TV is working just fine
Ps I am using a DIY irblaster

**Comment by chrisantmumo** [comment]
I have been to find the problem is I have to be near the machine for it to respond to the commands

**Comment by chrisantmumo** [comment]
Thank you for your help
