### ISSUE TITLE
Can the "new ir blaster" record / receive codes?

### ISSUE THREAD

**Issue by swinokur** [irplus-remote/irplus-codes.github.io#634]
now that #452 is solved (yay!), a follow up question - it seems like these devices also have an IR receiver built into them. 

I'm wondering if IRPlus can record codes using that hardware?

(@wasiliysoft does your application have the ability to record codes from the dongle?)

thanks!

**Comment by wasiliysoft** [comment]
@swinokur No, I didn't look into it, especially after I read in the article https://habr.com/ru/articles/494800 / that this receiver is not suitable for serious cases.

**Comment by swinokur** [comment]
thanks for the update!
